import React from 'react'
import RegisterServiceData from 'components/auth/register/service/RegisterServiceData'
import './RegisterService.scss'

/* This class was auto-generated by the JavaScriptWriter */
class RegisterService extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		RegisterServiceData.register(this)
	}

	componentWillUnmount() {
		RegisterServiceData.unregister()
	}

	render() {
		return (
			<div className='ap-registerservice'>
				RegisterService
			</div>
		)
	}

}
export default RegisterService
