package org.ap.auxpro.storage.intervention;

import org.ap.common.storage.IFieldEnum;
import org.ap.common.validators.IValidator;
import org.ap.auxpro.internal.Validators;

/* This class was auto-generated by the JavaWriter */
public enum InterventionFields implements IFieldEnum {

	AUXILIARY_ID ("auxiliaryId", "String", Validators.DEFAULT.VALIDATOR),
	END_DATE ("endDate", "List<Integer>", Validators.NON_NULL.VALIDATOR),
	SKILL_CHILDREN_GAME ("skillChildrenGame", "Integer", Validators.DEFAULT.VALIDATOR),
	SKILL_HOUSE ("skillHouse", "Integer", Validators.DEFAULT.VALIDATOR),
	LAST_UPDATE_DATE ("lastUpdateDate", "List<Integer>", Validators.DEFAULT.VALIDATOR),
	SAD_STATUS_CHANGED ("sadStatusChanged", "List<Integer>", Validators.DEFAULT.VALIDATOR),
	SKILL_BEAUTY ("skillBeauty", "Integer", Validators.DEFAULT.VALIDATOR),
	MISSION_TYPE ("missionType", "String", Validators.NON_NULL.VALIDATOR),
	SKILL_HANDICAP ("skillHandicap", "Integer", Validators.DEFAULT.VALIDATOR),
	SKILL_ILLNESS ("skillIllness", "Integer", Validators.DEFAULT.VALIDATOR),
	CUSTOMER_ID ("customerId", "String", Validators.DEFAULT.VALIDATOR),
	SKILL_CHILDREN_SCHOOL ("skillChildrenSchool", "Integer", Validators.DEFAULT.VALIDATOR),
	SAD_STATUS ("sadStatus", "String", Validators.DEFAULT.VALIDATOR),
	START_TIME ("startTime", "Integer", Validators.TIME_ARRAY.VALIDATOR),
	ID ("id", "String", Validators.DEFAULT.VALIDATOR),
	SERVICE_ID ("serviceId", "String", Validators.DEFAULT.VALIDATOR),
	SKILL_CHILDREN_KEEP ("skillChildrenKeep", "Integer", Validators.DEFAULT.VALIDATOR),
	SKILL_OLD_CARE ("skillOldCare", "Integer", Validators.DEFAULT.VALIDATOR),
	PERIOD ("period", "String", Validators.NON_NULL.VALIDATOR),
	SKILL_NURSING ("skillNursing", "Integer", Validators.DEFAULT.VALIDATOR),
	SKILL_CHILDREN_CARE ("skillChildrenCare", "Integer", Validators.DEFAULT.VALIDATOR),
	SKILL_FOOD ("skillFood", "Integer", Validators.DEFAULT.VALIDATOR),
	CREATION_DATE ("creationDate", "List<Integer>", Validators.DEFAULT.VALIDATOR),
	SKILL_COMPANY ("skillCompany", "Integer", Validators.DEFAULT.VALIDATOR),
	SKILL_TRANSPORT ("skillTransport", "Integer", Validators.DEFAULT.VALIDATOR),
	SKILL_CLOTHES ("skillClothes", "Integer", Validators.DEFAULT.VALIDATOR),
	DAYS ("days", "String", Validators.NON_EMPTY_ARRAY.VALIDATOR),
	END_TIME ("endTime", "Integer", Validators.TIME_ARRAY.VALIDATOR),
	SKILL_PET ("skillPet", "Integer", Validators.DEFAULT.VALIDATOR),
	HIDE_TO_SAD ("hideToSad", "Boolean", Validators.DEFAULT.VALIDATOR),
	START_DATE ("startDate", "List<Integer>", Validators.NON_NULL.VALIDATOR),
	;

	private String _id;
	private String _type;
	private IValidator _validator;

	private InterventionFields(String id, String type, IValidator validator) {
		_id = id;
		_type = type;
		_validator = validator;
	}

	public String getId() {
		return _id;
	}

	public String getType() {
		return _type;
	}

	public IValidator getValidator() {
		return _validator;
	}

	public static InterventionFields byId(String id) {
		for (InterventionFields value : InterventionFields.values()) {
			if (value.getId().equals(id)) {
				return value;
			}
		}
		return null;
	}

}
