package org.ap.auxpro.storage.intervention;

import java.util.Date;
import java.util.List;

/* This class was auto-generated by the JavaWriter */
public class InterventionData {

	public String auxiliaryId;
	public Date endDate;
	public Integer skillChildrenGame;
	public Integer skillHouse;
	public Date lastUpdateDate;
	public Date sadStatusChanged;
	public Integer skillBeauty;
	public String missionType;
	public Integer skillHandicap;
	public Integer skillIllness;
	public String customerId;
	public Integer skillChildrenSchool;
	public String sadStatus;
	public List<Integer> startTime;
	public String id;
	public String serviceId;
	public Integer skillChildrenKeep;
	public Integer skillOldCare;
	public String period;
	public Integer skillNursing;
	public Integer skillChildrenCare;
	public Integer skillFood;
	public Date creationDate;
	public Integer skillCompany;
	public Integer skillTransport;
	public Integer skillClothes;
	public List<String> days;
	public List<Integer> endTime;
	public Integer skillPet;
	public Boolean hideToSad;
	public Date startDate;

	public String getAuxiliaryId() {
		return this.auxiliaryId;
	}

	public void setAuxiliaryId(String auxiliaryId) {
		this.auxiliaryId = auxiliaryId;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getSkillChildrenGame() {
		return this.skillChildrenGame;
	}

	public void setSkillChildrenGame(Integer skillChildrenGame) {
		this.skillChildrenGame = skillChildrenGame;
	}

	public Integer getSkillHouse() {
		return this.skillHouse;
	}

	public void setSkillHouse(Integer skillHouse) {
		this.skillHouse = skillHouse;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Date getSadStatusChanged() {
		return this.sadStatusChanged;
	}

	public void setSadStatusChanged(Date sadStatusChanged) {
		this.sadStatusChanged = sadStatusChanged;
	}

	public Integer getSkillBeauty() {
		return this.skillBeauty;
	}

	public void setSkillBeauty(Integer skillBeauty) {
		this.skillBeauty = skillBeauty;
	}

	public String getMissionType() {
		return this.missionType;
	}

	public void setMissionType(String missionType) {
		this.missionType = missionType;
	}

	public Integer getSkillHandicap() {
		return this.skillHandicap;
	}

	public void setSkillHandicap(Integer skillHandicap) {
		this.skillHandicap = skillHandicap;
	}

	public Integer getSkillIllness() {
		return this.skillIllness;
	}

	public void setSkillIllness(Integer skillIllness) {
		this.skillIllness = skillIllness;
	}

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public Integer getSkillChildrenSchool() {
		return this.skillChildrenSchool;
	}

	public void setSkillChildrenSchool(Integer skillChildrenSchool) {
		this.skillChildrenSchool = skillChildrenSchool;
	}

	public String getSadStatus() {
		return this.sadStatus;
	}

	public void setSadStatus(String sadStatus) {
		this.sadStatus = sadStatus;
	}

	public List<Integer> getStartTime() {
		return this.startTime;
	}

	public void setStartTime(List<Integer> startTime) {
		this.startTime = startTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(String serviceId) {
		this.serviceId = serviceId;
	}

	public Integer getSkillChildrenKeep() {
		return this.skillChildrenKeep;
	}

	public void setSkillChildrenKeep(Integer skillChildrenKeep) {
		this.skillChildrenKeep = skillChildrenKeep;
	}

	public Integer getSkillOldCare() {
		return this.skillOldCare;
	}

	public void setSkillOldCare(Integer skillOldCare) {
		this.skillOldCare = skillOldCare;
	}

	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public Integer getSkillNursing() {
		return this.skillNursing;
	}

	public void setSkillNursing(Integer skillNursing) {
		this.skillNursing = skillNursing;
	}

	public Integer getSkillChildrenCare() {
		return this.skillChildrenCare;
	}

	public void setSkillChildrenCare(Integer skillChildrenCare) {
		this.skillChildrenCare = skillChildrenCare;
	}

	public Integer getSkillFood() {
		return this.skillFood;
	}

	public void setSkillFood(Integer skillFood) {
		this.skillFood = skillFood;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Integer getSkillCompany() {
		return this.skillCompany;
	}

	public void setSkillCompany(Integer skillCompany) {
		this.skillCompany = skillCompany;
	}

	public Integer getSkillTransport() {
		return this.skillTransport;
	}

	public void setSkillTransport(Integer skillTransport) {
		this.skillTransport = skillTransport;
	}

	public Integer getSkillClothes() {
		return this.skillClothes;
	}

	public void setSkillClothes(Integer skillClothes) {
		this.skillClothes = skillClothes;
	}

	public List<String> getDays() {
		return this.days;
	}

	public void setDays(List<String> days) {
		this.days = days;
	}

	public List<Integer> getEndTime() {
		return this.endTime;
	}

	public void setEndTime(List<Integer> endTime) {
		this.endTime = endTime;
	}

	public Integer getSkillPet() {
		return this.skillPet;
	}

	public void setSkillPet(Integer skillPet) {
		this.skillPet = skillPet;
	}

	public Boolean getHideToSad() {
		return this.hideToSad;
	}

	public void setHideToSad(Boolean hideToSad) {
		this.hideToSad = hideToSad;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

}
