package org.ap.auxpro.storage.intervention;

import java.util.Date;
import java.util.List;

/* This class was auto-generated by the JavaWriter */
public class InterventionData {

	public String period;
	public String auxiliaryId;
	public Date endDate;
	public Date lastUpdateDate;
	public Date sadStatusChanged;
	public Date creationDate;
	public String missionType;
	public String customerId;
	public List<String> days;
	public List<String> diplomas;
	public String sadStatus;
	public List<Integer> startTime;
	public String id;
	public List<Integer> endTime;
	public String serviceId;
	public Boolean hideToSad;
	public Date startDate;

	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public String getAuxiliaryId() {
		return this.auxiliaryId;
	}

	public void setAuxiliaryId(String auxiliaryId) {
		this.auxiliaryId = auxiliaryId;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Date getSadStatusChanged() {
		return this.sadStatusChanged;
	}

	public void setSadStatusChanged(Date sadStatusChanged) {
		this.sadStatusChanged = sadStatusChanged;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public String getMissionType() {
		return this.missionType;
	}

	public void setMissionType(String missionType) {
		this.missionType = missionType;
	}

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public List<String> getDays() {
		return this.days;
	}

	public void setDays(List<String> days) {
		this.days = days;
	}

	public List<String> getDiplomas() {
		return this.diplomas;
	}

	public void setDiplomas(List<String> diplomas) {
		this.diplomas = diplomas;
	}

	public String getSadStatus() {
		return this.sadStatus;
	}

	public void setSadStatus(String sadStatus) {
		this.sadStatus = sadStatus;
	}

	public List<Integer> getStartTime() {
		return this.startTime;
	}

	public void setStartTime(List<Integer> startTime) {
		this.startTime = startTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public List<Integer> getEndTime() {
		return this.endTime;
	}

	public void setEndTime(List<Integer> endTime) {
		this.endTime = endTime;
	}

	public String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(String serviceId) {
		this.serviceId = serviceId;
	}

	public Boolean getHideToSad() {
		return this.hideToSad;
	}

	public void setHideToSad(Boolean hideToSad) {
		this.hideToSad = hideToSad;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

}
