package org.ap.auxpro.storage.customer;

import org.ap.common.validators.EValidators;
import org.ap.common.validators.IValidator;

/* This class was auto-generated by the JavaWriter */
public enum CustomerFields {

	LAST_NAME ("lastName", "String", EValidators.NON_EMPTY_STRING.getValidator()),
	COUNTRY ("country", "String", EValidators.NON_EMPTY_STRING.getValidator()),
	CIVILITY ("civility", "String", EValidators.NON_NULL.getValidator()),
	ADDRESS ("address", "String", EValidators.NON_EMPTY_STRING.getValidator()),
	SKILL_NURSING ("skillNursing", "Integer", EValidators.DEFAULT.getValidator()),
	CITY ("city", "String", EValidators.NON_EMPTY_STRING.getValidator()),
	LATTITUDE ("lattitude", "Double", EValidators.DEFAULT.getValidator()),
	LAST_UPDATE_DATE ("lastUpdateDate", "List<Integer>", EValidators.DEFAULT.getValidator()),
	POSTAL_CODE ("postalCode", "String", EValidators.POSTAL_CODE.getValidator()),
	CREATION_DATE ("creationDate", "List<Integer>", EValidators.DEFAULT.getValidator()),
	BIRTH_DATE ("birthDate", "List<Integer>", EValidators.BEFORE_TODAY.getValidator()),
	SKILL_CHILDHOOD ("skillChildhood", "Integer", EValidators.DEFAULT.getValidator()),
	SKILL_COMPAGNY ("skillCompagny", "Integer", EValidators.DEFAULT.getValidator()),
	SKILL_SHOPPING ("skillShopping", "Integer", EValidators.DEFAULT.getValidator()),
	FIRST_NAME ("firstName", "String", EValidators.NON_EMPTY_STRING.getValidator()),
	NATIONALITY ("nationality", "String", EValidators.NON_NULL.getValidator()),
	PHONE ("phone", "String", EValidators.PHONE.getValidator()),
	SKILL_ADMINISTRATIVE ("skillAdministrative", "Integer", EValidators.DEFAULT.getValidator()),
	SKILL_HOUSEWORK ("skillHousework", "Integer", EValidators.DEFAULT.getValidator()),
	SKILL_DOITYOURSELF ("skillDoityourself", "Integer", EValidators.DEFAULT.getValidator()),
	ID ("id", "String", EValidators.DEFAULT.getValidator()),
	SERVICE_ID ("serviceId", "String", EValidators.DEFAULT.getValidator()),
	EMAIL ("email", "String", EValidators.DEFAULT.getValidator()),
	LONGITUDE ("longitude", "Double", EValidators.DEFAULT.getValidator()),
	;

	private String _id;
	private String _type;
	private IValidator<?> _validator;

	private  CustomerFields(String id, String type, IValidator<?> validator) {
		_id = id;
		_type = type;
		_validator = validator;
	}

	public String getId() {
		return _id;
	}

	public String getType() {
		return _type;
	}

	public IValidator<?> getValidator() {
		return _validator;
	}

	public static CustomerFields byId(String id) {
		for (CustomerFields value : CustomerFields.values()) {
			if (value.getId().equals(id)) {
				return value;
			}
		}
		return null;
	}

}
