package org.ap.auxpro.storage.customer;

import org.ap.common.storage.IFieldEnum;
import org.ap.common.validators.IValidator;
import org.ap.auxpro.internal.Validators;

/* This class was auto-generated by the JavaWriter */
public enum CustomerFields implements IFieldEnum {

	LAST_NAME ("lastName", "String", Validators.NON_EMPTY_STRING.VALIDATOR),
	COUNTRY ("country", "String", Validators.NON_EMPTY_STRING.VALIDATOR),
	CIVILITY ("civility", "String", Validators.NON_NULL.VALIDATOR),
	ADDRESS ("address", "String", Validators.NON_EMPTY_STRING.VALIDATOR),
	CITY ("city", "String", Validators.NON_EMPTY_STRING.VALIDATOR),
	LATTITUDE ("lattitude", "Double", Validators.DEFAULT.VALIDATOR),
	LAST_UPDATE_DATE ("lastUpdateDate", "List<Integer>", Validators.DEFAULT.VALIDATOR),
	POSTAL_CODE ("postalCode", "String", Validators.POSTAL_CODE.VALIDATOR),
	CREATION_DATE ("creationDate", "List<Integer>", Validators.DEFAULT.VALIDATOR),
	BIRTH_DATE ("birthDate", "List<Integer>", Validators.BEFORE_TODAY.VALIDATOR),
	FIRST_NAME ("firstName", "String", Validators.NON_EMPTY_STRING.VALIDATOR),
	NATIONALITY ("nationality", "String", Validators.NON_NULL.VALIDATOR),
	PHONE ("phone", "String", Validators.PHONE.VALIDATOR),
	ID ("id", "String", Validators.DEFAULT.VALIDATOR),
	SERVICE_ID ("serviceId", "String", Validators.DEFAULT.VALIDATOR),
	CATEGORY ("category", "String", Validators.NON_NULL.VALIDATOR),
	EMAIL ("email", "String", Validators.DEFAULT.VALIDATOR),
	LONGITUDE ("longitude", "Double", Validators.DEFAULT.VALIDATOR),
	;

	private String _id;
	private String _type;
	private IValidator _validator;

	private CustomerFields(String id, String type, IValidator validator) {
		_id = id;
		_type = type;
		_validator = validator;
	}

	public String getId() {
		return _id;
	}

	public String getType() {
		return _type;
	}

	public IValidator getValidator() {
		return _validator;
	}

	public static CustomerFields byId(String id) {
		for (CustomerFields value : CustomerFields.values()) {
			if (value.getId().equals(id)) {
				return value;
			}
		}
		return null;
	}

}
