package org.ap.auxpro.storage.customer;

import java.util.Date;

/* This class was auto-generated by the JavaWriter */
public class CustomerData {

	public String lastName;
	public String country;
	public String civility;
	public String city;
	public Integer skillChildrenGame;
	public Integer skillHouse;
	public Date lastUpdateDate;
	public String postalCode;
	public Integer skillBeauty;
	public Integer skillHandicap;
	public Integer skillIllness;
	public Integer skillChildrenSchool;
	public String id;
	public String serviceId;
	public Integer skillChildrenKeep;
	public String email;
	public Integer skillOldCare;
	public Double longitude;
	public String address;
	public Integer skillNursing;
	public Integer skillChildrenCare;
	public Double lattitude;
	public Integer skillFood;
	public Integer skillCompany;
	public Date creationDate;
	public Date birthDate;
	public String firstName;
	public String nationality;
	public String phone;
	public Integer skillTransport;
	public Integer skillClothes;
	public String category;
	public Integer skillPet;

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCivility() {
		return this.civility;
	}

	public void setCivility(String civility) {
		this.civility = civility;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Integer getSkillChildrenGame() {
		return this.skillChildrenGame;
	}

	public void setSkillChildrenGame(Integer skillChildrenGame) {
		this.skillChildrenGame = skillChildrenGame;
	}

	public Integer getSkillHouse() {
		return this.skillHouse;
	}

	public void setSkillHouse(Integer skillHouse) {
		this.skillHouse = skillHouse;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public Integer getSkillBeauty() {
		return this.skillBeauty;
	}

	public void setSkillBeauty(Integer skillBeauty) {
		this.skillBeauty = skillBeauty;
	}

	public Integer getSkillHandicap() {
		return this.skillHandicap;
	}

	public void setSkillHandicap(Integer skillHandicap) {
		this.skillHandicap = skillHandicap;
	}

	public Integer getSkillIllness() {
		return this.skillIllness;
	}

	public void setSkillIllness(Integer skillIllness) {
		this.skillIllness = skillIllness;
	}

	public Integer getSkillChildrenSchool() {
		return this.skillChildrenSchool;
	}

	public void setSkillChildrenSchool(Integer skillChildrenSchool) {
		this.skillChildrenSchool = skillChildrenSchool;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(String serviceId) {
		this.serviceId = serviceId;
	}

	public Integer getSkillChildrenKeep() {
		return this.skillChildrenKeep;
	}

	public void setSkillChildrenKeep(Integer skillChildrenKeep) {
		this.skillChildrenKeep = skillChildrenKeep;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getSkillOldCare() {
		return this.skillOldCare;
	}

	public void setSkillOldCare(Integer skillOldCare) {
		this.skillOldCare = skillOldCare;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getSkillNursing() {
		return this.skillNursing;
	}

	public void setSkillNursing(Integer skillNursing) {
		this.skillNursing = skillNursing;
	}

	public Integer getSkillChildrenCare() {
		return this.skillChildrenCare;
	}

	public void setSkillChildrenCare(Integer skillChildrenCare) {
		this.skillChildrenCare = skillChildrenCare;
	}

	public Double getLattitude() {
		return this.lattitude;
	}

	public void setLattitude(Double lattitude) {
		this.lattitude = lattitude;
	}

	public Integer getSkillFood() {
		return this.skillFood;
	}

	public void setSkillFood(Integer skillFood) {
		this.skillFood = skillFood;
	}

	public Integer getSkillCompany() {
		return this.skillCompany;
	}

	public void setSkillCompany(Integer skillCompany) {
		this.skillCompany = skillCompany;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Integer getSkillTransport() {
		return this.skillTransport;
	}

	public void setSkillTransport(Integer skillTransport) {
		this.skillTransport = skillTransport;
	}

	public Integer getSkillClothes() {
		return this.skillClothes;
	}

	public void setSkillClothes(Integer skillClothes) {
		this.skillClothes = skillClothes;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Integer getSkillPet() {
		return this.skillPet;
	}

	public void setSkillPet(Integer skillPet) {
		this.skillPet = skillPet;
	}

}
