package org.ap.auxpro.internal;

/* This class was auto-generated by the JavaWriter */
public enum ETokenType {

	REGISTER,
	RECOVER,
	CHANGEMAIL,
	CHANGEMAIL_CONFIRM,
	;
	private ETokenType() {
	}

	public static ETokenType byId(String id) {
		for (ETokenType type: ETokenType.values()) {
			if (type.name().toUpperCase().equals(id)) {
				return type;
			}
		}
		return null;
	}

}
