import React from 'react'
import RegisterConfirmEmailData from 'components/auth/register/confirm/RegisterConfirmEmailData'
import './RegisterConfirmEmail.scss'

import RegisterConfirm from 'components/auth/register/confirm/RegisterConfirm'

/* This class was auto-generated by the JavaScriptWriter */
class RegisterConfirmEmail extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		RegisterConfirmEmailData.register(this, this.props.params.email)
	}

	componentWillUnmount() {
		RegisterConfirmEmailData.unregister()
	}

	render() {
		return (
			<RegisterConfirm email={this.props.params.email} />
		)
	}

}
export default RegisterConfirmEmail
