import AppHelper from 'helpers/AppHelper'
import { BaseData } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class RegisterConfirmEmailData extends BaseData {

	register(obj, email) {
		super.register(obj)
		
		this.obj.state = {}
	}

	unregister() {
	}

}
var RegisterConfirmEmailObj = new RegisterConfirmEmailData()
export default RegisterConfirmEmailObj
