import React from 'react'
import AppLogoData from 'components//AppLogoData'
import './AppLogo.scss'

/* This class was auto-generated by the JavaScriptWriter */
class AppLogo extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		AppLogoData.register(this)
	}

	componentWillUnmount() {
		AppLogoData.unregister()
	}

	render() {
		return (
			<div className='ap-applogo' onClick={this.onClick} />
		)
	}

}
export default AppLogo
