import React from 'react'
import RedirectData from 'components//RedirectData'
import './Redirect.scss'

/* This class was auto-generated by the JavaScriptWriter */
class Redirect extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		RedirectData.register(this)
	}

	componentWillUnmount() {
		RedirectData.unregister()
	}

	render() {
		return (
			<div className='ap-redirect'>
				Redirect
			</div>
		)
	}

}
export default Redirect
