import AppHelper from 'helpers/AppHelper'
import AuthHelper from 'helpers/AuthHelper'
import AuxiliaryHelper from 'helpers/AuxiliaryHelper'

import { BaseData, Utils } from 'ap-react-bootstrap'


let ICONS = {
	HOME: '/assets/images/markers/gmap-marker-home.png',
	GEOZONE: '/assets/images/markers/gmap-marker-geozone.png',
	OFFER: '/assets/images/markers/gmap-marker-customer-pink.png',
	INTERVENTION: '/assets/images/markers/gmap-marker-customer-blue.png',
	SERVICE: '/assets/images/markers/gmap-marker-service-green.png',
	SERVICE_ANY: '/assets/images/markers/gmap-marker-service-red.png'
}

let INFO_TYPE = {
	HOME: 'H',
	GEOZONE: 'G',
	CUSTOMER: 'C',
	OFFER: 'O',
	SERVICE: 'S'
}

/* This class was auto-generated by the JavaScriptWriter */
class AuxiliaryZoneData extends BaseData {

	register(obj) {
		super.register(obj)
		
		this.onMarkerClicked = this._onMarkerClicked.bind(this)

		this.auxliary = AuxiliaryHelper.getData(AuthHelper.getEntityId())

		this.obj.state = {
			auxliary: this.auxliary,
			centerLattitude: Number(this.auxliary.lattitude),
			centerLongitude: Number(this.auxliary.longitude)
		}

		this.homeMarkers = [ this.buildHomeMarker() ]
		this.obj.state.markers = this.homeMarkers
	}

	unregister() {
	}

	buildHomeMarker() { 
		return {
			lattitude: Number(this.auxliary.lattitude),
			longitude: Number(this.auxliary.longitude),
			title: 'Mon domicile',
			type: INFO_TYPE.HOME,
			icon: ICONS.HOME,
			onClick: this.onMarkerClicked.bind(this)
		}
	}

	_onMarkerClicked(marker) {
		console.log(marker)
		switch(marker.type) {
		case INFO_TYPE.HOME:
			break
		}
		this.setState({ 
			infoType: marker.type,
		})
	}

}
var AuxiliaryZoneObj = new AuxiliaryZoneData()
AuxiliaryZoneObj.ICONS = ICONS
AuxiliaryZoneObj.INFO_TYPE = INFO_TYPE
export default AuxiliaryZoneObj

