import React from 'react'
import ServiceData from 'components/service/ServiceData'
import './Service.scss'

/* This class was auto-generated by the JavaScriptWriter */
class Service extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		ServiceData.register(this)
	}

	componentWillUnmount() {
		ServiceData.unregister()
	}

	render() {
		return (
			<div className='ap-service'>
				Service
				{this.props.children}
			</div>
		)
	}

}
export default Service
