import React from 'react'
import ContactData from 'components/infos/contact/ContactData'
import './Contact.scss'
import { Panel } from 'ap-react-bootstrap'


/* This class was auto-generated by the JavaScriptWriter */
class Contact extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		ContactData.register(this)
	}

	componentWillUnmount() {
		ContactData.unregister()
	}

	render() {
		return (
			<div className='ap-contact'>
				<Panel>
					<h2>Contact</h2>
	                <a href='mailto:contact@auxpros.fr' target='_top'>contact@auxpros.fr</a>				
				</Panel>
			</div>
		)
	}

}
export default Contact
