import React from 'react'
import ContactData from 'components/infos/contact/ContactData'
import './Contact.scss'

/* This class was auto-generated by the JavaScriptWriter */
class Contact extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		ContactData.register(this)
	}

	componentWillUnmount() {
		ContactData.unregister()
	}

	render() {
		return (
			<div className='ap-contact'>
				Contact
			</div>
		)
	}

}
export default Contact
