import AppHelper from 'helpers/AppHelper'
import { BaseData } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class AuxiliaryInfosEditInfosData extends BaseData {

	register(obj) {
		super.register(obj)
		
		this.obj.state = {}
	}

	unregister() {
	}

}
let AuxiliaryInfosEditInfosObj = new AuxiliaryInfosEditInfosData()
export default AuxiliaryInfosEditInfosObj
