import React from 'react'
import AuthData from 'components/auth/AuthData'
import './Auth.scss'

/* This class was auto-generated by the JavaScriptWriter */
class Auth extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		AuthData.register(this)
	}

	componentWillUnmount() {
		AuthData.unregister()
	}

	render() {
		return (
			<div className='ap-auth'>
				{this.props.children}
			</div>
		)
	}

}
export default Auth
