import { Validators } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class AuxiliaryFields {

	static get DIPLOMA_IMAGE() {
		return {
			key: 'diplomaImage',
			type: 'string',
		}
	}

	static get COUNTRY() {
		return {
			key: 'country',
			type: 'string',
		}
	}

	static get LAST_NAME() {
		return {
			key: 'lastName',
			type: 'string',
		}
	}

	static get DIPLOMA_VALIDATED() {
		return {
			key: 'diplomaValidated',
			type: 'boolean',
		}
	}

	static get CIVILITY() {
		return {
			key: 'civility',
			type: 'string',
		}
	}

	static get CITY() {
		return {
			key: 'city',
			type: 'string',
		}
	}

	static get POSTAL_CODE() {
		return {
			key: 'postalCode',
			type: 'number',
		}
	}

	static get IS_TUTO_SKIPPED() {
		return {
			key: 'isTutoSkipped',
			type: 'boolean',
		}
	}

	static get DESCRIPTION() {
		return {
			key: 'description',
			type: 'string',
		}
	}

	static get SOCIAL_NUMBER() {
		return {
			key: 'socialNumber',
			type: 'string',
		}
	}

	static get ACCOUNT_EXPIRY_DATE() {
		return {
			key: 'accountExpiryDate',
			type: 'number',
		}
	}

	static get SKILL_SHOPPING() {
		return {
			key: 'skillShopping',
			type: 'number',
		}
	}

	static get NOTIFY_OFFERS_SMS() {
		return {
			key: 'notifyOffersSms',
			type: 'boolean',
		}
	}

	static get NOTIFY_AUXPROS() {
		return {
			key: 'notifyAuxpros',
			type: 'boolean',
		}
	}

	static get BIRTH_COUNTRY() {
		return {
			key: 'birthCountry',
			type: 'string',
		}
	}

	static get ADDRESS_CHECKED() {
		return {
			key: 'addressChecked',
			type: 'boolean',
		}
	}

	static get DIPLOMA() {
		return {
			key: 'diploma',
			type: 'string',
		}
	}

	static get SKILL_DOITYOURSELF() {
		return {
			key: 'skillDoityourself',
			type: 'number',
		}
	}

	static get ID() {
		return {
			key: 'id',
			type: 'string',
		}
	}

	static get EMAIL() {
		return {
			key: 'email',
			type: 'string',
		}
	}

	static get LONGITUDE() {
		return {
			key: 'longitude',
			type: 'number',
		}
	}

	static get SKILL_NURSING() {
		return {
			key: 'skillNursing',
			type: 'number',
		}
	}

	static get ADDRESS() {
		return {
			key: 'address',
			type: 'string',
		}
	}

	static get LATTITUDE() {
		return {
			key: 'lattitude',
			type: 'number',
		}
	}

	static get ACCOUNT_TYPE() {
		return {
			key: 'accountType',
			type: 'string',
		}
	}

	static get NOTIFY_PARTNERS() {
		return {
			key: 'notifyPartners',
			type: 'boolean',
		}
	}

	static get BIRTH_CITY() {
		return {
			key: 'birthCity',
			type: 'string',
		}
	}

	static get AVATAR() {
		return {
			key: 'avatar',
			type: 'string',
		}
	}

	static get ARE_SKILL_SET() {
		return {
			key: 'areSkillSet',
			type: 'boolean',
		}
	}

	static get BIRTH_DATE() {
		return {
			key: 'birthDate',
			type: 'number',
		}
	}

	static get SKILL_CHILDHOOD() {
		return {
			key: 'skillChildhood',
			type: 'number',
		}
	}

	static get SKILL_COMPAGNY() {
		return {
			key: 'skillCompagny',
			type: 'number',
		}
	}

	static get FIRST_NAME() {
		return {
			key: 'firstName',
			type: 'string',
		}
	}

	static get SKILL_ANSWERS() {
		return {
			key: 'skillAnswers',
			type: 'number',
		}
	}

	static get NATIONALITY() {
		return {
			key: 'nationality',
			type: 'string',
		}
	}

	static get IS_ENTREPRENEUR() {
		return {
			key: 'isEntrepreneur',
			type: 'boolean',
		}
	}

	static get PHONE() {
		return {
			key: 'phone',
			type: 'string',
		}
	}

	static get SKILL_ADMINISTRATIVE() {
		return {
			key: 'skillAdministrative',
			type: 'number',
		}
	}

	static get PHONE_CHECKED() {
		return {
			key: 'phoneChecked',
			type: 'boolean',
		}
	}

	static get SKILL_HOUSEWORK() {
		return {
			key: 'skillHousework',
			type: 'number',
		}
	}

	static get ID_CARD_NUMBER() {
		return {
			key: 'idCardNumber',
			type: 'number',
		}
	}

	static get EMAIL_CHECKED() {
		return {
			key: 'emailChecked',
			type: 'boolean',
		}
	}

	static get NOTIFY_OFFERS_MAIL() {
		return {
			key: 'notifyOffersMail',
			type: 'boolean',
		}
	}

}
export default AuxiliaryFields
