import validators from 'utils/validators'
import Civility from 'utils/constants/Civility'
import PeopleCategory from 'utils/constants/PeopleCategory'

/* This class was auto-generated by the JavaScriptWriter */
/* DO NOT MODIFY THIS FILE IT WILL BE REGENERATED IN THE FUTURE */
class CustomerFields {

	static get LAST_NAME() {
		return _LAST_NAME
	}

	static get COUNTRY() {
		return _COUNTRY
	}

	static get CIVILITY() {
		return _CIVILITY
	}

	static get CITY() {
		return _CITY
	}

	static get SKILL_CHILDREN_GAME() {
		return _SKILL_CHILDREN_GAME
	}

	static get SKILL_HOUSE() {
		return _SKILL_HOUSE
	}

	static get LAST_UPDATE_DATE() {
		return _LAST_UPDATE_DATE
	}

	static get POSTAL_CODE() {
		return _POSTAL_CODE
	}

	static get SKILL_BEAUTY() {
		return _SKILL_BEAUTY
	}

	static get SKILL_HANDICAP() {
		return _SKILL_HANDICAP
	}

	static get SKILL_ILLNESS() {
		return _SKILL_ILLNESS
	}

	static get SKILL_CHILDREN_SCHOOL() {
		return _SKILL_CHILDREN_SCHOOL
	}

	static get ID() {
		return _ID
	}

	static get SERVICE_ID() {
		return _SERVICE_ID
	}

	static get SKILL_CHILDREN_KEEP() {
		return _SKILL_CHILDREN_KEEP
	}

	static get EMAIL() {
		return _EMAIL
	}

	static get SKILL_OLD_CARE() {
		return _SKILL_OLD_CARE
	}

	static get LONGITUDE() {
		return _LONGITUDE
	}

	static get ADDRESS() {
		return _ADDRESS
	}

	static get SKILL_NURSING() {
		return _SKILL_NURSING
	}

	static get SKILL_CHILDREN_CARE() {
		return _SKILL_CHILDREN_CARE
	}

	static get LATTITUDE() {
		return _LATTITUDE
	}

	static get SKILL_FOOD() {
		return _SKILL_FOOD
	}

	static get SKILL_COMPANY() {
		return _SKILL_COMPANY
	}

	static get CREATION_DATE() {
		return _CREATION_DATE
	}

	static get BIRTH_DATE() {
		return _BIRTH_DATE
	}

	static get FIRST_NAME() {
		return _FIRST_NAME
	}

	static get NATIONALITY() {
		return _NATIONALITY
	}

	static get PHONE() {
		return _PHONE
	}

	static get SKILL_TRANSPORT() {
		return _SKILL_TRANSPORT
	}

	static get SKILL_CLOTHES() {
		return _SKILL_CLOTHES
	}

	static get CATEGORY() {
		return _CATEGORY
	}

	static get SKILL_PET() {
		return _SKILL_PET
	}

	static get VALUES() {
		return [
			_LAST_NAME,
			_COUNTRY,
			_CIVILITY,
			_CITY,
			_SKILL_CHILDREN_GAME,
			_SKILL_HOUSE,
			_LAST_UPDATE_DATE,
			_POSTAL_CODE,
			_SKILL_BEAUTY,
			_SKILL_HANDICAP,
			_SKILL_ILLNESS,
			_SKILL_CHILDREN_SCHOOL,
			_ID,
			_SERVICE_ID,
			_SKILL_CHILDREN_KEEP,
			_EMAIL,
			_SKILL_OLD_CARE,
			_LONGITUDE,
			_ADDRESS,
			_SKILL_NURSING,
			_SKILL_CHILDREN_CARE,
			_LATTITUDE,
			_SKILL_FOOD,
			_SKILL_COMPANY,
			_CREATION_DATE,
			_BIRTH_DATE,
			_FIRST_NAME,
			_NATIONALITY,
			_PHONE,
			_SKILL_TRANSPORT,
			_SKILL_CLOTHES,
			_CATEGORY,
			_SKILL_PET,
		]
	}

	static get(id) {
		for (let i = 0 ; i < CustomerFields.VALUES.length ; i++) {
			if (CustomerFields.VALUES[i].key === id) {
				return CustomerFields.VALUES[i]
			}
		}
	}

}
let _LAST_NAME = {
	key: 'lastName',
	type: 'string',
	validator: validators.NON_EMPTY_STRING,
}
let _COUNTRY = {
	key: 'country',
	type: 'string',
	validator: validators.NON_EMPTY_STRING,
}
let _CIVILITY = {
	key: 'civility',
	type: 'string',
	values: Civility.VALUES,
	validator: validators.NON_NULL,
}
let _CITY = {
	key: 'city',
	type: 'string',
	validator: validators.NON_EMPTY_STRING,
}
let _SKILL_CHILDREN_GAME = {
	key: 'skillChildrenGame',
	type: 'number',
	validator: validators.DEFAULT,
}
let _SKILL_HOUSE = {
	key: 'skillHouse',
	type: 'number',
	validator: validators.DEFAULT,
}
let _LAST_UPDATE_DATE = {
	key: 'lastUpdateDate',
	type: 'Date',
	validator: validators.DEFAULT,
}
let _POSTAL_CODE = {
	key: 'postalCode',
	type: 'string',
	validator: validators.POSTAL_CODE,
}
let _SKILL_BEAUTY = {
	key: 'skillBeauty',
	type: 'number',
	validator: validators.DEFAULT,
}
let _SKILL_HANDICAP = {
	key: 'skillHandicap',
	type: 'number',
	validator: validators.DEFAULT,
}
let _SKILL_ILLNESS = {
	key: 'skillIllness',
	type: 'number',
	validator: validators.DEFAULT,
}
let _SKILL_CHILDREN_SCHOOL = {
	key: 'skillChildrenSchool',
	type: 'number',
	validator: validators.DEFAULT,
}
let _ID = {
	key: 'id',
	type: 'string',
	validator: validators.DEFAULT,
}
let _SERVICE_ID = {
	key: 'serviceId',
	type: 'string',
	validator: validators.DEFAULT,
}
let _SKILL_CHILDREN_KEEP = {
	key: 'skillChildrenKeep',
	type: 'number',
	validator: validators.DEFAULT,
}
let _EMAIL = {
	key: 'email',
	type: 'string',
	validator: validators.DEFAULT,
}
let _SKILL_OLD_CARE = {
	key: 'skillOldCare',
	type: 'number',
	validator: validators.DEFAULT,
}
let _LONGITUDE = {
	key: 'longitude',
	type: 'number',
	validator: validators.DEFAULT,
}
let _ADDRESS = {
	key: 'address',
	type: 'string',
	validator: validators.NON_EMPTY_STRING,
}
let _SKILL_NURSING = {
	key: 'skillNursing',
	type: 'number',
	validator: validators.DEFAULT,
}
let _SKILL_CHILDREN_CARE = {
	key: 'skillChildrenCare',
	type: 'number',
	validator: validators.DEFAULT,
}
let _LATTITUDE = {
	key: 'lattitude',
	type: 'number',
	validator: validators.DEFAULT,
}
let _SKILL_FOOD = {
	key: 'skillFood',
	type: 'number',
	validator: validators.DEFAULT,
}
let _SKILL_COMPANY = {
	key: 'skillCompany',
	type: 'number',
	validator: validators.DEFAULT,
}
let _CREATION_DATE = {
	key: 'creationDate',
	type: 'Date',
	validator: validators.DEFAULT,
}
let _BIRTH_DATE = {
	key: 'birthDate',
	type: 'Date',
	validator: validators.BEFORE_TODAY,
}
let _FIRST_NAME = {
	key: 'firstName',
	type: 'string',
	validator: validators.NON_EMPTY_STRING,
}
let _NATIONALITY = {
	key: 'nationality',
	type: 'string',
	validator: validators.NON_NULL,
}
let _PHONE = {
	key: 'phone',
	type: 'string',
	validator: validators.PHONE,
}
let _SKILL_TRANSPORT = {
	key: 'skillTransport',
	type: 'number',
	validator: validators.DEFAULT,
}
let _SKILL_CLOTHES = {
	key: 'skillClothes',
	type: 'number',
	validator: validators.DEFAULT,
}
let _CATEGORY = {
	key: 'category',
	type: 'string',
	values: PeopleCategory.VALUES,
	validator: validators.NON_NULL,
}
let _SKILL_PET = {
	key: 'skillPet',
	type: 'number',
	validator: validators.DEFAULT,
}
export default CustomerFields
