import validators from 'utils/validators'
import GeozoneType from 'utils/constants/GeozoneType'

/* This class was auto-generated by the JavaScriptWriter */
/* DO NOT MODIFY THIS FILE IT WILL BE REGENERATED IN THE FUTURE */
class GeozoneFields {

	static get AUXILIARY_ID() {
		return _AUXILIARY_ID
	}

	static get ADDRESS() {
		return _ADDRESS
	}

	static get LATTITUDE() {
		return _LATTITUDE
	}

	static get CITY() {
		return _CITY
	}

	static get LAST_UPDATE_DATE() {
		return _LAST_UPDATE_DATE
	}

	static get POSTAL_CODE() {
		return _POSTAL_CODE
	}

	static get ID() {
		return _ID
	}

	static get TYPE() {
		return _TYPE
	}

	static get RADIUS() {
		return _RADIUS
	}

	static get CREATION_DATE() {
		return _CREATION_DATE
	}

	static get LONGITUDE() {
		return _LONGITUDE
	}

	static get VALUES() {
		return [
			_AUXILIARY_ID,
			_ADDRESS,
			_LATTITUDE,
			_CITY,
			_LAST_UPDATE_DATE,
			_POSTAL_CODE,
			_ID,
			_TYPE,
			_RADIUS,
			_CREATION_DATE,
			_LONGITUDE,
		]
	}

	static get(id) {
		for (let i = 0 ; i < GeozoneFields.VALUES.length ; i++) {
			if (GeozoneFields.VALUES[i].key === id) {
				return GeozoneFields.VALUES[i]
			}
		}
	}

}
let _AUXILIARY_ID = {
	key: 'auxiliaryId',
	type: 'string',
	validator: validators.DEFAULT,
}
let _ADDRESS = {
	key: 'address',
	type: 'string',
	validator: validators.NON_EMPTY_STRING,
}
let _LATTITUDE = {
	key: 'lattitude',
	type: 'number',
	validator: validators.NON_NULL,
}
let _CITY = {
	key: 'city',
	type: 'string',
	validator: validators.NON_EMPTY_STRING,
}
let _LAST_UPDATE_DATE = {
	key: 'lastUpdateDate',
	type: 'Date',
	validator: validators.DEFAULT,
}
let _POSTAL_CODE = {
	key: 'postalCode',
	type: 'string',
	validator: validators.POSTAL_CODE,
}
let _ID = {
	key: 'id',
	type: 'string',
	validator: validators.DEFAULT,
}
let _TYPE = {
	key: 'type',
	type: 'string',
	values: GeozoneType.VALUES,
	validator: validators.NON_NULL,
}
let _RADIUS = {
	key: 'radius',
	type: 'number',
	validator: validators.POSITIVE_INTEGER,
}
let _CREATION_DATE = {
	key: 'creationDate',
	type: 'Date',
	validator: validators.DEFAULT,
}
let _LONGITUDE = {
	key: 'longitude',
	type: 'number',
	validator: validators.NON_NULL,
}
export default GeozoneFields
