import { Validators } from 'ap-react-bootstrap'
import GeozoneType from 'utils/constants/GeozoneType'

/* This class was auto-generated by the JavaScriptWriter */
class GeozoneFields {

	static get AUXILIARY_ID() {
		return _AUXILIARY_ID
	}

	static get ADDRESS() {
		return _ADDRESS
	}

	static get LATTITUDE() {
		return _LATTITUDE
	}

	static get CITY() {
		return _CITY
	}

	static get POSTAL_CODE() {
		return _POSTAL_CODE
	}

	static get ID() {
		return _ID
	}

	static get TYPE() {
		return _TYPE
	}

	static get RADIUS() {
		return _RADIUS
	}

	static get LONGITUDE() {
		return _LONGITUDE
	}

	static get VALUES() {
		return [
			_AUXILIARY_ID,
			_ADDRESS,
			_LATTITUDE,
			_CITY,
			_POSTAL_CODE,
			_ID,
			_TYPE,
			_RADIUS,
			_LONGITUDE,
		]
	}

	static get(id) {
		for (let i = 0 ; i < GeozoneFields.VALUES.length ; i++) {
			if (GeozoneFields.VALUES[i].key === id) {
				return GeozoneFields.VALUES[i]
			}
		}
	}

}
let _AUXILIARY_ID = {
	key: 'auxiliaryId',
	type: 'string',
}
let _ADDRESS = {
	key: 'address',
	type: 'string',
}
let _LATTITUDE = {
	key: 'lattitude',
	type: 'number',
}
let _CITY = {
	key: 'city',
	type: 'string',
}
let _POSTAL_CODE = {
	key: 'postalCode',
	type: 'string',
}
let _ID = {
	key: 'id',
	type: 'string',
}
let _TYPE = {
	key: 'type',
	type: 'string',
	values: GeozoneType.VALUES,
}
let _RADIUS = {
	key: 'radius',
	type: 'number',
}
let _LONGITUDE = {
	key: 'longitude',
	type: 'number',
}
export default GeozoneFields
