import { Validators } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class GeozoneFields {

	static get AUXILIARY_ID() {
		return {
			key: 'auxiliaryId',
			type: 'string',
		}
	}

	static get ADDRESS() {
		return {
			key: 'address',
			type: 'string',
		}
	}

	static get LATTITUDE() {
		return {
			key: 'lattitude',
			type: 'number',
		}
	}

	static get CITY() {
		return {
			key: 'city',
			type: 'string',
		}
	}

	static get POSTAL_CODE() {
		return {
			key: 'postalCode',
			type: 'string',
		}
	}

	static get ID() {
		return {
			key: 'id',
			type: 'string',
		}
	}

	static get TYPE() {
		return {
			key: 'type',
			type: 'string',
		}
	}

	static get RADIUS() {
		return {
			key: 'radius',
			type: 'number',
		}
	}

	static get LONGITUDE() {
		return {
			key: 'longitude',
			type: 'number',
		}
	}

}
export default GeozoneFields
