import { Validators } from 'ap-react-bootstrap'
import InterventionStatus from 'utils/constants/InterventionStatus'

/* This class was auto-generated by the JavaScriptWriter */
class InterventionFields {

	static get PERIOD() {
		return {
			key: 'period',
			type: 'string',
		}
	}

	static get AUXILIARY_ID() {
		return {
			key: 'auxiliaryId',
			type: 'string',
		}
	}

	static get END_DATE() {
		return {
			key: 'endDate',
			type: 'number',
		}
	}

	static get SAD_STATUS_CHANGED() {
		return {
			key: 'sadStatusChanged',
			type: 'number',
		}
	}

	static get CUSTOMER_ID() {
		return {
			key: 'customerId',
			type: 'string',
		}
	}

	static get SAD_STATUS() {
		return {
			key: 'sadStatus',
			type: 'string',
			values: InterventionStatus.VALUES,
		}
	}

	static get DAYS() {
		return {
			key: 'days',
			type: 'string',
		}
	}

	static get START_TIME() {
		return {
			key: 'startTime',
			type: 'number',
		}
	}

	static get END_TIME() {
		return {
			key: 'endTime',
			type: 'number',
		}
	}

	static get ID() {
		return {
			key: 'id',
			type: 'string',
		}
	}

	static get SERVICE_ID() {
		return {
			key: 'serviceId',
			type: 'string',
		}
	}

	static get HIDE_TO_SAD() {
		return {
			key: 'hideToSad',
			type: 'boolean',
		}
	}

	static get START_DATE() {
		return {
			key: 'startDate',
			type: 'number',
		}
	}

}
export default InterventionFields
