import { Validators } from 'ap-react-bootstrap'
import RecurencePeriod from 'utils/constants/RecurencePeriod'
import InterventionStatus from 'utils/constants/InterventionStatus'

/* This class was auto-generated by the JavaScriptWriter */
/* DO NOT MODIFY THIS FILE IT WILL BE REGENERATED IN THE FUTURE */
class InterventionFields {

	static get PERIOD() {
		return _PERIOD
	}

	static get AUXILIARY_ID() {
		return _AUXILIARY_ID
	}

	static get END_DATE() {
		return _END_DATE
	}

	static get LAST_UPDATE_DATE() {
		return _LAST_UPDATE_DATE
	}

	static get SAD_STATUS_CHANGED() {
		return _SAD_STATUS_CHANGED
	}

	static get CREATION_DATE() {
		return _CREATION_DATE
	}

	static get CUSTOMER_ID() {
		return _CUSTOMER_ID
	}

	static get SAD_STATUS() {
		return _SAD_STATUS
	}

	static get DAYS() {
		return _DAYS
	}

	static get START_TIME() {
		return _START_TIME
	}

	static get END_TIME() {
		return _END_TIME
	}

	static get ID() {
		return _ID
	}

	static get SERVICE_ID() {
		return _SERVICE_ID
	}

	static get HIDE_TO_SAD() {
		return _HIDE_TO_SAD
	}

	static get START_DATE() {
		return _START_DATE
	}

	static get VALUES() {
		return [
			_PERIOD,
			_AUXILIARY_ID,
			_END_DATE,
			_LAST_UPDATE_DATE,
			_SAD_STATUS_CHANGED,
			_CREATION_DATE,
			_CUSTOMER_ID,
			_SAD_STATUS,
			_DAYS,
			_START_TIME,
			_END_TIME,
			_ID,
			_SERVICE_ID,
			_HIDE_TO_SAD,
			_START_DATE,
		]
	}

	static get(id) {
		for (let i = 0 ; i < InterventionFields.VALUES.length ; i++) {
			if (InterventionFields.VALUES[i].key === id) {
				return InterventionFields.VALUES[i]
			}
		}
	}

}
let _PERIOD = {
	key: 'period',
	type: 'string',
	values: RecurencePeriod.VALUES,
}
let _AUXILIARY_ID = {
	key: 'auxiliaryId',
	type: 'string',
}
let _END_DATE = {
	key: 'endDate',
	type: 'number',
}
let _LAST_UPDATE_DATE = {
	key: 'lastUpdateDate',
	type: 'Date',
}
let _SAD_STATUS_CHANGED = {
	key: 'sadStatusChanged',
	type: 'number',
}
let _CREATION_DATE = {
	key: 'creationDate',
	type: 'Date',
}
let _CUSTOMER_ID = {
	key: 'customerId',
	type: 'string',
}
let _SAD_STATUS = {
	key: 'sadStatus',
	type: 'string',
	values: InterventionStatus.VALUES,
}
let _DAYS = {
	key: 'days',
	type: 'string',
}
let _START_TIME = {
	key: 'startTime',
	type: 'number',
}
let _END_TIME = {
	key: 'endTime',
	type: 'number',
}
let _ID = {
	key: 'id',
	type: 'string',
}
let _SERVICE_ID = {
	key: 'serviceId',
	type: 'string',
}
let _HIDE_TO_SAD = {
	key: 'hideToSad',
	type: 'boolean',
}
let _START_DATE = {
	key: 'startDate',
	type: 'number',
}
export default InterventionFields
