import validators from 'utils/validators'

/* This class was auto-generated by the JavaScriptWriter */
/* DO NOT MODIFY THIS FILE IT WILL BE REGENERATED IN THE FUTURE */
class PromotioncodeFields {

  static get LAST_UPDATE_DATE() {
    return _LAST_UPDATE_DATE
  }

  static get VALIDITY_DATE() {
    return _VALIDITY_DATE
  }

  static get NAME() {
    return _NAME
  }

  static get ID() {
    return _ID
  }

  static get CREATION_DATE() {
    return _CREATION_DATE
  }

  static get VALUES() {
    return [
    	_LAST_UPDATE_DATE,
    	_VALIDITY_DATE,
    	_NAME,
    	_ID,
    	_CREATION_DATE,
    ]
  }

  static get(id) {
    for (let i = 0 ; i < PromotioncodeFields.VALUES.length ; i++) {
    	if (PromotioncodeFields.VALUES[i].key === id) {
    		return PromotioncodeFields.VALUES[i]
    	}
    }
  }

}
let _LAST_UPDATE_DATE = {
	key: 'lastUpdateDate',
	type: 'Date',
	validator: validators.DEFAULT,
}
let _VALIDITY_DATE = {
	key: 'validityDate',
	type: 'Date',
	validator: validators.DEFAULT,
}
let _NAME = {
	key: 'name',
	type: 'string',
	validator: validators.DEFAULT,
}
let _ID = {
	key: 'id',
	type: 'string',
	validator: validators.DEFAULT,
}
let _CREATION_DATE = {
	key: 'creationDate',
	type: 'Date',
	validator: validators.DEFAULT,
}
export default PromotioncodeFields
