import { Validators } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class ServiceFields {

	static get COUNTRY() {
		return {
			key: 'country',
			type: 'string',
		}
	}

	static get ADDRESS() {
		return {
			key: 'address',
			type: 'string',
		}
	}

	static get CITY() {
		return {
			key: 'city',
			type: 'string',
		}
	}

	static get LATTITUDE() {
		return {
			key: 'lattitude',
			type: 'number',
		}
	}

	static get ACCOUNT_TYPE() {
		return {
			key: 'accountType',
			type: 'string',
		}
	}

	static get POSTAL_CODE() {
		return {
			key: 'postalCode',
			type: 'number',
		}
	}

	static get IS_TUTO_SKIPPED() {
		return {
			key: 'isTutoSkipped',
			type: 'boolean',
		}
	}

	static get NOTIFY_PARTNERS() {
		return {
			key: 'notifyPartners',
			type: 'boolean',
		}
	}

	static get AVATAR() {
		return {
			key: 'avatar',
			type: 'string',
		}
	}

	static get ACCOUNT_EXPIRY_DATE() {
		return {
			key: 'accountExpiryDate',
			type: 'number',
		}
	}

	static get SIRET() {
		return {
			key: 'siret',
			type: 'string',
		}
	}

	static get NOTIFY_AUXPROS() {
		return {
			key: 'notifyAuxpros',
			type: 'boolean',
		}
	}

	static get PHONE() {
		return {
			key: 'phone',
			type: 'string',
		}
	}

	static get PHONE_CHECKED() {
		return {
			key: 'phoneChecked',
			type: 'boolean',
		}
	}

	static get FUNCTION() {
		return {
			key: 'function',
			type: 'string',
		}
	}

	static get ADDRESS_CHECKED() {
		return {
			key: 'addressChecked',
			type: 'boolean',
		}
	}

	static get EMAIL_CHECKED() {
		return {
			key: 'emailChecked',
			type: 'boolean',
		}
	}

	static get ID() {
		return {
			key: 'id',
			type: 'string',
		}
	}

	static get SOCIAL_REASON() {
		return {
			key: 'socialReason',
			type: 'string',
		}
	}

	static get EMAIL() {
		return {
			key: 'email',
			type: 'string',
		}
	}

	static get LONGITUDE() {
		return {
			key: 'longitude',
			type: 'number',
		}
	}

}
export default ServiceFields
