import React from 'react'
import ServiceHomeData from 'components/service/home/ServiceHomeData'
import './ServiceHome.scss'

/* This class was auto-generated by the JavaScriptWriter */
class ServiceHome extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		ServiceHomeData.register(this)
	}

	componentWillUnmount() {
		ServiceHomeData.unregister()
	}

	render() {
		return (
			<div className='ap-servicehome'>
				ServiceHome
			</div>
		)
	}

}
export default ServiceHome
