package org.ap.auxpro.storage.apmail;

/* This class was auto-generated by the JavaWriter */
public class ApmailData {

	public String subject;
	public String id;
	public String content;

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
