import React from 'react'
import ServiceInfosEditAccountData from 'components/service/infos/edit/account/ServiceInfosEditAccountData'
import './ServiceInfosEditAccount.scss'

/* This class was auto-generated by the JavaScriptWriter */
class ServiceInfosEditAccount extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		ServiceInfosEditAccountData.register(this)
	}

	componentWillUnmount() {
		ServiceInfosEditAccountData.unregister()
	}

	render() {
		return (
			<div className='ap-serviceinfoseditaccount'>
				ServiceInfosEditAccount
			</div>
		)
	}

}
export default ServiceInfosEditAccount
