import AppHelper from 'helpers/AppHelper'
import { BaseData } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class ServiceTutoData extends BaseData {

	register(obj) {
		super.register(obj)
		
		this.obj.state = {}
	}

	unregister() {
	}

}
var ServiceTutoObj = new ServiceTutoData()
export default ServiceTutoObj
