import React from 'react'
import ServiceTutoData from 'components/service/tuto/ServiceTutoData'
import './ServiceTuto.scss'

/* This class was auto-generated by the JavaScriptWriter */
class ServiceTuto extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		ServiceTutoData.register(this)
	}

	componentWillUnmount() {
		ServiceTutoData.unregister()
	}

	render() {
		return (
			<div className='ap-servicetuto'>
				ServiceTuto
			</div>
		)
	}

}
export default ServiceTuto
