import { Dispatcher, StoreRegistry } from 'ap-flux'
import AuthHelper from 'helpers/AuthHelper'

/* This class was auto-generated by the JavaScriptWriter */
/* DO NOT MODIFY THIS FILE IT WILL BE REGENERATED IN THE FUTURE */
class AuxiliaryHelper {

	register(id, obj, callback) {
		StoreRegistry.register('REST_STORE/auxiliary' + (id ? '/' + id : ''), obj, callback);
	}

	unregister(obj) {
		StoreRegistry.unregister('REST_STORE', obj);
	}

	getAuxiliarys() {
		return Dispatcher.issue('GET_AUXILIARYS', {token: AuthHelper.getToken()});
	}

	postAuxiliary(data) {
		return Dispatcher.issue('POST_AUXILIARY', {token: AuthHelper.getToken(), data: data});
	}

	getAuxiliary(id) {
		return Dispatcher.issue('GET_AUXILIARY', {token: AuthHelper.getToken(), id: id});
	}

	putAuxiliary(data) {
		return Dispatcher.issue('PUT_AUXILIARY', {token: AuthHelper.getToken(), id: data.id, data: data});
	}

	postAuxiliaryQuestionary(data) {
		return Dispatcher.issue('POST_AUXILIARY_QUESTIONARY', {token: AuthHelper.getToken(), id: data.id, data: data});
	}

	getServiceAuxiliarys(serviceId) {
		return Dispatcher.issue('GET_SERVICE_AUXILIARYS', {token: AuthHelper.getToken(), serviceId: serviceId});
	}

	getData(id) {
		return StoreRegistry.getStore('REST_STORE').getData('/auxiliary' + (id ? '/' + id : ''));
	}

}
var AuxiliaryObj = new AuxiliaryHelper()
export default AuxiliaryObj
