import { Dispatcher, StoreRegistry } from 'ap-flux'
import AuthHelper from 'helpers/AuthHelper'
import { Utils } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
/* DO NOT MODIFY THIS FILE IT WILL BE REGENERATED IN THE FUTURE */
class HelptopicHelper {

	register(id, obj, callback) {
		StoreRegistry.register('REST_STORE/helptopic' + (id ? '/' + id : ''), obj, callback);
	}

	unregister(obj) {
		StoreRegistry.unregister('REST_STORE', obj);
	}

	getHelpTopics() {
		return Dispatcher.issue('GET_HELP_TOPICS', {token: Utils.encode('guest', 'guest')});
	}

	getData(id) {
		return StoreRegistry.getStore('REST_STORE').getData('/helptopic' + (id ? '/' + id : ''));
	}

}
var HelptopicObj = new HelptopicHelper()
export default HelptopicObj
