import { Dispatcher, StoreRegistry } from 'ap-flux'
import AuthHelper from 'helpers/AuthHelper'
import { Utils } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class HelpfaqHelper {

	register(id, obj, callback) {
		StoreRegistry.register('REST_STORE/helpfaq' + (id ? '/' + id : ''), obj, callback);
	}

	unregister(obj) {
		StoreRegistry.unregister('REST_STORE', obj);
	}

	getHelpFaqs() {
		return Dispatcher.issue('GET_HELP_FAQS', {token: Utils.encode('guest', 'guest')});
	}

	getData(id) {
		return StoreRegistry.getStore('REST_STORE').getData('/helpfaq' + (id ? '/' + id : ''));
	}

}
var HelpfaqObj = new HelpfaqHelper()
export default HelpfaqObj
