import { Dispatcher, StoreRegistry } from 'ap-flux'
import AuthHelper from 'helpers/AuthHelper'

/* This class was auto-generated by the JavaScriptWriter */
class IndisponibilityHelper {

	register(id, obj, callback) {
		StoreRegistry.register('REST_STORE/indisponibility' + (id ? '/' + id : ''), obj, callback);
	}

	unregister(obj) {
		StoreRegistry.unregister('REST_STORE', obj);
	}

	getAuxiliaryIndisponibilitys(auxiliaryId) {
		return Dispatcher.issue('GET_AUXILIARY_INDISPONIBILITYS', {token: AuthHelper.getToken(), auxiliaryId: auxiliaryId});
	}

	postIndisponibility(data) {
		return Dispatcher.issue('POST_INDISPONIBILITY', {token: AuthHelper.getToken(), data: data});
	}

	getIndisponibility(id) {
		return Dispatcher.issue('GET_INDISPONIBILITY', {token: AuthHelper.getToken(), id: id});
	}

	putIndisponibility(data) {
		return Dispatcher.issue('PUT_INDISPONIBILITY', {token: AuthHelper.getToken(), id: data.id, data: data});
	}

	deleteIndisponibility(id) {
		return Dispatcher.issue('DELETE_INDISPONIBILITY', {token: AuthHelper.getToken(), id: id});
	}

	getData(id) {
		return StoreRegistry.getStore('REST_STORE').getData('/indisponibility' + (id ? '/' + id : ''));
	}

}
var IndisponibilityObj = new IndisponibilityHelper()
export default IndisponibilityObj
