import { Dispatcher, StoreRegistry } from 'ap-flux'
import AuthHelper from 'helpers/AuthHelper'

/* This class was auto-generated by the JavaScriptWriter */
class OfferHelper {

	register(obj, callback) {
		StoreRegistry.register('REST_STORE/offer', obj, callback);
	}

	unregister(obj) {
		StoreRegistry.unregister('REST_STORE', obj);
	}

	getAuxiliaryOffers(auxiliaryId) {
		return Dispatcher.issue('GET_AUXILIARY_OFFERS', {token: AuthHelper.getToken(), auxiliaryId: auxiliaryId});
	}

	getInterventionOffers(interventionId) {
		return Dispatcher.issue('GET_INTERVENTION_OFFERS', {token: AuthHelper.getToken(), interventionId: interventionId});
	}

	postOffer(data) {
		return Dispatcher.issue('POST_OFFER', {token: AuthHelper.getToken(), data: data});
	}

	getOffer(id) {
		return Dispatcher.issue('GET_OFFER', {token: AuthHelper.getToken(), id: id});
	}

	putOffer(data) {
		return Dispatcher.issue('PUT_OFFER', {token: AuthHelper.getToken(), id: data.id, data: data});
	}

	deleteOffer(id) {
		return Dispatcher.issue('DELETE_OFFER', {token: AuthHelper.getToken(), id: id});
	}

	getServiceOffers(serviceId) {
		return Dispatcher.issue('GET_SERVICE_OFFERS', {token: AuthHelper.getToken(), serviceId: serviceId});
	}

	getData(id) {
		return StoreRegistry.getStore('REST_STORE').getData('/offer' + (id ? '/' + id : ''));
	}

}
var OfferObj = new OfferHelper()
export default OfferObj
