package org.ap.auxpro.rest.filter;

import javax.annotation.Priority;
import javax.ws.rs.Priorities;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.Response.Status;
import javax.ws.rs.ext.Provider;
import org.ap.auxpro.storage.apauth.ApauthCollection;
import org.ap.auxpro.storage.apauth.ApauthData;
import org.ap.common.web.auth.APSecured;
import org.ap.common.web.auth.bean.APAuthBean;
import org.ap.common.web.auth.data.IAPAuthData;
import org.ap.common.web.auth.filter.BasicAuthRequestFilter;
import org.ap.common.web.exception.APWebException;

/* This class was auto-generated by the JavaWriter */
@Provider
@APSecured
@Priority(Priorities.AUTHORIZATION)
public class AuthorizationRequestFilter extends BasicAuthRequestFilter {

	@Override
	public IAPAuthData resolveAuthData(APAuthBean authBean) throws APWebException {
		ApauthData dataAuth = ApauthCollection.getByUsername(authBean.username);
		if (dataAuth == null) {
			dataAuth = ApauthCollection.getByEmail(authBean.username);
		}
		
		if (
			dataAuth == null ||
			!authBean.password.equals(dataAuth.getPassword()) ||
			dataAuth.getRegistered() == null ||
			!dataAuth.getRegistered()
		) {
			throw new WebApplicationException(Status.UNAUTHORIZED);
		}
		
		return dataAuth;
	}

}
