import React from 'react'
import ServiceInfosData from 'components/service/infos/ServiceInfosData'
import './ServiceInfos.scss'

/* This class was auto-generated by the JavaScriptWriter */
class ServiceInfos extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		ServiceInfosData.register(this)
	}

	componentWillUnmount() {
		ServiceInfosData.unregister()
	}

	render() {
		return (
			<div className='ap-serviceinfos'>
				ServiceInfos
			</div>
		)
	}

}
export default ServiceInfos
