import React from 'react'
import AuxiliaryHomeData from 'components/auxiliary/home/AuxiliaryHomeData'
import './AuxiliaryHome.scss'

/* This class was auto-generated by the JavaScriptWriter */
class AuxiliaryHome extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		AuxiliaryHomeData.register(this)
	}

	componentWillUnmount() {
		AuxiliaryHomeData.unregister()
	}

	render() {
		return (
			<div className='ap-auxiliaryhome'>
				AuxiliaryHome
			</div>
		)
	}

}
export default AuxiliaryHome
