import AppHelper from 'helpers/AppHelper'
import { BaseData } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class RecoverConfirmEmailData extends BaseData {

	register(obj, email) {
		super.register(obj)
	}

	unregister() {
	}

}
var RecoverConfirmEmailObj = new RecoverConfirmEmailData()
export default RecoverConfirmEmailObj
