import React from 'react'
import ConfidentialData from 'components/infos/confidential/ConfidentialData'
import './Confidential.scss'

/* This class was auto-generated by the JavaScriptWriter */
class Confidential extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		ConfidentialData.register(this)
	}

	componentWillUnmount() {
		ConfidentialData.unregister()
	}

	render() {
		return (
			<div className='ap-confidential'>
				Confidential
			</div>
		)
	}

}
export default Confidential
