import React from 'react'
import AuxiliaryInfosEditAccountData from './AuxiliaryInfosEditAccountData'
import './AuxiliaryInfosEditAccount.scss'

/* This class was auto-generated by the JavaScriptWriter */
class AuxiliaryInfosEditAccount extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		AuxiliaryInfosEditAccountData.register(this)
	}

	componentWillUnmount() {
		AuxiliaryInfosEditAccountData.unregister()
	}

	render() {
		return (
			<div className='ap-auxiliaryinfoseditaccount'>
				AuxiliaryInfosEditAccount
			</div>
		)
	}

}
export default AuxiliaryInfosEditAccount
