import React from 'react'
import AuxiliaryInfosEditPersoData from './AuxiliaryInfosEditPersoData'
import './AuxiliaryInfosEditPerso.scss'

/* This class was auto-generated by the JavaScriptWriter */
class AuxiliaryInfosEditPerso extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		AuxiliaryInfosEditPersoData.register(this)
	}

	componentWillUnmount() {
		AuxiliaryInfosEditPersoData.unregister()
	}

	render() {
		return (
			<div className='ap-auxiliaryinfoseditperso'>
				AuxiliaryInfosEditPerso
			</div>
		)
	}

}
export default AuxiliaryInfosEditPerso
