package org.ap.auxpro.storage.promotioncode;

import org.ap.common.storage.IFieldEnum;
import org.ap.common.validators.ValidatorProvider;
import org.ap.auxpro.internal.Validators;

/* This class was auto-generated by the JavaWriter */
public enum PromotioncodeFields implements IFieldEnum {

	LAST_UPDATE_DATE ("lastUpdateDate", "List<Integer>", new Validators.DEFAULT()),
	VALIDITY_DATE ("validityDate", "List<Integer>", new Validators.DEFAULT()),
	NAME ("name", "String", new Validators.DEFAULT()),
	ID ("id", "String", new Validators.DEFAULT()),
	CREATION_DATE ("creationDate", "List<Integer>", new Validators.DEFAULT()),
	;

	private String _id;
	private String _type;
	private ValidatorProvider _validator;

	private PromotioncodeFields(String id, String type, ValidatorProvider validator) {
		_id = id;
		_type = type;
		_validator = validator;
	}

	public String getId() {
		return _id;
	}

	public String getType() {
		return _type;
	}

	public ValidatorProvider getValidator() {
		return _validator;
	}

	public static PromotioncodeFields byId(String id) {
		for (PromotioncodeFields value : PromotioncodeFields.values()) {
			if (value.getId().equals(id)) {
				return value;
			}
		}
		return null;
	}

}
