package org.ap.auxpro.storage.service;

import org.ap.common.storage.IFieldEnum;
import org.ap.common.validators.ValidatorProvider;
import org.ap.auxpro.internal.Validators;

/* This class was auto-generated by the JavaWriter */
public enum ServiceFields implements IFieldEnum {

	COUNTRY ("country", "String", new Validators.NON_EMPTY_STRING()),
	ADDRESS ("address", "String", new Validators.NON_EMPTY_STRING()),
	CITY ("city", "String", new Validators.NON_EMPTY_STRING()),
	LATTITUDE ("lattitude", "Double", new Validators.DEFAULT()),
	LAST_UPDATE_DATE ("lastUpdateDate", "List<Integer>", new Validators.DEFAULT()),
	POSTAL_CODE ("postalCode", "String", new Validators.POSTAL_CODE()),
	ACCOUNT_TYPE ("accountType", "String", new Validators.DEFAULT()),
	IS_TUTO_SKIPPED ("isTutoSkipped", "Boolean", new Validators.DEFAULT()),
	NOTIFY_PARTNERS ("notifyPartners", "Boolean", new Validators.DEFAULT()),
	AVATAR ("avatar", "String", new Validators.DEFAULT()),
	ACCOUNT_EXPIRY_DATE ("accountExpiryDate", "List<Integer>", new Validators.DEFAULT()),
	CREATION_DATE ("creationDate", "List<Integer>", new Validators.DEFAULT()),
	SIRET ("siret", "String", new Validators.SIRET_NUMBER()),
	NOTIFY_AUXPROS ("notifyAuxpros", "Boolean", new Validators.DEFAULT()),
	PHONE ("phone", "String", new Validators.PHONE()),
	FUNCTION ("function", "String", new Validators.NON_NULL()),
	PROFIL_COMPLETED ("profilCompleted", "Boolean", new Validators.DEFAULT()),
	ID ("id", "String", new Validators.DEFAULT()),
	SOCIAL_REASON ("socialReason", "String", new Validators.NON_EMPTY_STRING()),
	LONGITUDE ("longitude", "Double", new Validators.DEFAULT()),
	;

	private String _id;
	private String _type;
	private ValidatorProvider _validator;

	private ServiceFields(String id, String type, ValidatorProvider validator) {
		_id = id;
		_type = type;
		_validator = validator;
	}

	public String getId() {
		return _id;
	}

	public String getType() {
		return _type;
	}

	public ValidatorProvider getValidator() {
		return _validator;
	}

	public static ServiceFields byId(String id) {
		for (ServiceFields value : ServiceFields.values()) {
			if (value.getId().equals(id)) {
				return value;
			}
		}
		return null;
	}

}
