package org.ap.auxpro.storage.service;

import java.util.Date;

/* This class was auto-generated by the JavaWriter */
public class ServiceData {

	public String authId;
	public String country;
	public String address;
	public String city;
	public Double lattitude;
	public Date lastUpdateDate;
	public String postalCode;
	public String accountType;
	public Boolean isTutoSkipped;
	public Boolean notifyPartners;
	public String avatar;
	public Date accountExpiryDate;
	public Date creationDate;
	public String siret;
	public Boolean notifyAuxpros;
	public String phone;
	public String function;
	public Boolean profilCompleted;
	public String id;
	public String socialReason;
	public Double longitude;

	public String getAuthId() {
		return this.authId;
	}

	public void setAuthId(String authId) {
		this.authId = authId;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Double getLattitude() {
		return this.lattitude;
	}

	public void setLattitude(Double lattitude) {
		this.lattitude = lattitude;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	public Boolean getIsTutoSkipped() {
		return this.isTutoSkipped;
	}

	public void setIsTutoSkipped(Boolean isTutoSkipped) {
		this.isTutoSkipped = isTutoSkipped;
	}

	public Boolean getNotifyPartners() {
		return this.notifyPartners;
	}

	public void setNotifyPartners(Boolean notifyPartners) {
		this.notifyPartners = notifyPartners;
	}

	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public Date getAccountExpiryDate() {
		return this.accountExpiryDate;
	}

	public void setAccountExpiryDate(Date accountExpiryDate) {
		this.accountExpiryDate = accountExpiryDate;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public String getSiret() {
		return this.siret;
	}

	public void setSiret(String siret) {
		this.siret = siret;
	}

	public Boolean getNotifyAuxpros() {
		return this.notifyAuxpros;
	}

	public void setNotifyAuxpros(Boolean notifyAuxpros) {
		this.notifyAuxpros = notifyAuxpros;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	public Boolean getProfilCompleted() {
		return this.profilCompleted;
	}

	public void setProfilCompleted(Boolean profilCompleted) {
		this.profilCompleted = profilCompleted;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSocialReason() {
		return this.socialReason;
	}

	public void setSocialReason(String socialReason) {
		this.socialReason = socialReason;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

}
