
/* This class was auto-generated by the JavaScriptWriter */
class AccountType {

	static get BASIQUE() {
		return _BASIQUE
	}

	static get PREMIUM() {
		return _PREMIUM
	}

	static get VALUES() {
		return [
			_BASIQUE,
			_PREMIUM,
		]
	}

	static get(id) {
		return id && AccountType[id.toUpperCase()]
	}

}
let _BASIQUE = { key: 'Basique' }
let _PREMIUM = { key: 'Premium' }
export default AccountType
