
/* This class was auto-generated by the JavaScriptWriter */
/* DO NOT MODIFY THIS FILE IT WILL BE REGENERATED IN THE FUTURE */
class AuxiliaryStatus {

	static get AUTO() {
		return _AUTO
	}

	static get SALARY() {
		return _SALARY
	}

	static get BOTH() {
		return _BOTH
	}

	static get VALUES() {
		return [
			_AUTO,
			_SALARY,
			_BOTH,
		]
	}

	static get(id) {
		return id && AuxiliaryStatus[id.toUpperCase()]
	}

}
let _AUTO = { key: 'Auto' }
let _SALARY = { key: 'Salary' }
let _BOTH = { key: 'Both' }
export default AuxiliaryStatus
