
/* This class was auto-generated by the JavaScriptWriter */
class Civility {

	static get MR() {
		return _MR
	}

	static get MME() {
		return _MME
	}

	static get VALUES() {
		return [
			_MR,
			_MME,
		]
	}

	static get(id) {
		return id && Civility[id.toUpperCase()]
	}

}
let _MR = { key: 'Mr' }
let _MME = { key: 'Mme' }
export default Civility
