
/* This class was auto-generated by the JavaScriptWriter */
/* DO NOT MODIFY THIS FILE IT WILL BE REGENERATED IN THE FUTURE */
class InterventionStatus {

  static get PENDING() {
    return _PENDING
  }

  static get MATCHING() {
    return _MATCHING
  }

  static get ON_GOING() {
    return _ON_GOING
  }

  static get CANCELED() {
    return _CANCELED
  }

  static get VALUES() {
    return [
    	_PENDING,
    	_MATCHING,
    	_ON_GOING,
    	_CANCELED,
    ]
  }

  static get(id) {
    return id && InterventionStatus[id.toUpperCase()]
  }

}
const _PENDING = { key: 'Pending', keyName: 'PENDING' }
const _MATCHING = { key: 'Matching', keyName: 'MATCHING' }
const _ON_GOING = { key: 'OnGoing', keyName: 'ON_GOING' }
const _CANCELED = { key: 'Canceled', keyName: 'CANCELED' }
export default InterventionStatus
