
/* This class was auto-generated by the JavaScriptWriter */
class OfferStatusSad {

	static get PENDING() {
		return _PENDING
	}

	static get CANCELED() {
		return _CANCELED
	}

	static get CONFIRMED() {
		return _CONFIRMED
	}

	static get REJECTED() {
		return _REJECTED
	}

	static get VALUES() {
		return [
			_PENDING,
			_CANCELED,
			_CONFIRMED,
			_REJECTED,
		]
	}

	static get(id) {
		return id && OfferStatusSad[id.toUpperCase()]
	}

}
let _PENDING = { key: 'Pending' }
let _CANCELED = { key: 'Canceled' }
let _CONFIRMED = { key: 'Confirmed' }
let _REJECTED = { key: 'Rejected' }
export default OfferStatusSad
