
/* This class was auto-generated by the JavaScriptWriter */
class SocFunction {

	static get MAND() {
		return _MAND
	}

	static get PREST() {
		return _PREST
	}

	static get BOTH() {
		return _BOTH
	}

	static get VALUES() {
		return [
			_MAND,
			_PREST,
			_BOTH,
		]
	}

	static get(id) {
		return id && SocFunction[id.toUpperCase()]
	}

}
let _MAND = { key: 'MAND' }
let _PREST = { key: 'PREST' }
let _BOTH = { key: 'BOTH' }
export default SocFunction
