import AppHelper from 'helpers/AppHelper'
import { BaseData } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class AuxiliaryInfosEditQuestionaryData extends BaseData {

	register(obj) {
		super.register(obj)
		
		this.obj.state = {}
	}

	unregister() {
	}

}
var AuxiliaryInfosEditQuestionaryObj = new AuxiliaryInfosEditQuestionaryData()
export default AuxiliaryInfosEditQuestionaryObj
