import React from 'react'
import ServiceInterventionEditData from 'components/service/interventions/edit/ServiceInterventionEditData'
import './ServiceInterventionEdit.scss'

/* This class was auto-generated by the JavaScriptWriter */
class ServiceInterventionEdit extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		ServiceInterventionEditData.register(this, this.props.params.interventionId)
	}

	componentWillUnmount() {
		ServiceInterventionEditData.unregister()
	}

	render() {
		return (
			<div className='ap-serviceinterventionedit'>
				ServiceInterventionEdit - {this.props.params.interventionId}
			</div>
		)
	}

}
export default ServiceInterventionEdit
