import AppHelper from 'helpers/AppHelper'
import { BaseData } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class ServiceInterventionEditData extends BaseData {

	register(obj, interventionId) {
		super.register(obj)
		
		this.obj.state = {}
	}

	unregister() {
	}

}
var ServiceInterventionEditObj = new ServiceInterventionEditData()
export default ServiceInterventionEditObj
