package org.ap.auxpro.constants;

/* This class was auto-generated by the JavaWriter */
public enum EAuxiliaryStatus {

	_AUTO ("Auto"),
	_SALARY ("Salary"),
	_BOTH ("Both"),
	;

	private String _name;

	private  EAuxiliaryStatus(String name) {
		_name = name;
	}

	public String getName() {
		return _name;
	}

	public static EAuxiliaryStatus getByName(String name) {
		for (EAuxiliaryStatus value: EAuxiliaryStatus.values()) {
			if (value.getName().equals(name)) {
				return value;
			}
		}
		return null;
	}

}
