package org.ap.auxpro.constants;

/* This class was auto-generated by the JavaWriter */
public enum EGeozoneType {

	_AREA ("Area"),
	_CITY ("City"),
	;

	private String _name;

	private  EGeozoneType(String name) {
		_name = name;
	}

	public String getName() {
		return _name;
	}

	public static EGeozoneType getByName(String name) {
		for (EGeozoneType value: EGeozoneType.values()) {
			if (value.getName().equals(name)) {
				return value;
			}
		}
		return null;
	}

}
