package org.ap.auxpro.constants;

/* This class was auto-generated by the JavaWriter */
public enum EIndisponibilityRecurencePeriod {

	_HOURS ("Hours"),
	_DAYS ("Days"),
	_WEEK1 ("Week1"),
	_WEEK2 ("Week2"),
	_WEEK3 ("Week3"),
	_WEEK4 ("Week4"),
	;

	private String _name;

	private  EIndisponibilityRecurencePeriod(String name) {
		_name = name;
	}

	public String getName() {
		return _name;
	}

	public static EIndisponibilityRecurencePeriod getByName(String name) {
		for (EIndisponibilityRecurencePeriod value: EIndisponibilityRecurencePeriod.values()) {
			if (value.getName().equals(name)) {
				return value;
			}
		}
		return null;
	}

}
