package org.ap.auxpro.constants;

/* This class was auto-generated by the JavaWriter */
public enum EOfferStatusSad {

	_PENDING ("Pending"),
	_CANCELED ("Canceled"),
	_CONFIRMED ("Confirmed"),
	_REJECTED ("Rejected"),
	;

	private String _name;

	private EOfferStatusSad(String name) {
		_name = name;
	}

	public String getName() {
		return _name;
	}

	public static EOfferStatusSad getByName(String name) {
		for (EOfferStatusSad value: EOfferStatusSad.values()) {
			if (value.getName().equals(name)) {
				return value;
			}
		}
		return null;
	}

}
