package org.ap.auxpro.constants;

/* This class was auto-generated by the JavaWriter */
public enum EPeopleCategory {

	_OLD_PEOPLE ("old_people"),
	_CHILDREN ("children"),
	_HANDICAP ("handicap"),
	_AUTONOMOUS ("autonomous"),
	;

	private String _name;

	private EPeopleCategory(String name) {
		_name = name;
	}

	public String getName() {
		return _name;
	}

	public static EPeopleCategory getByName(String name) {
		for (EPeopleCategory value: EPeopleCategory.values()) {
			if (value.getName().equals(name)) {
				return value;
			}
		}
		return null;
	}

}
