package org.ap.auxpro.constants;

/* This class was auto-generated by the JavaWriter */
public enum ERecurencePeriod {

	_O_N_E ("ONE"),
	_P1_W ("P1W"),
	_P2_W ("P2W"),
	_P3_W ("P3W"),
	_P4_W ("P4W"),
	;

	private String _name;

	private  ERecurencePeriod(String name) {
		_name = name;
	}

	public String getName() {
		return _name;
	}

	public static ERecurencePeriod getByName(String name) {
		for (ERecurencePeriod value: ERecurencePeriod.values()) {
			if (value.getName().equals(name)) {
				return value;
			}
		}
		return null;
	}

}
