package org.ap.auxpro.constants;

/* This class was auto-generated by the JavaWriter */
public enum ESkills {

	_SKILL_HOUSEWORK ("skillHousework"),
	_SKILL_CHILDHOOD ("skillChildhood"),
	_SKILL_SHOPPING ("skillShopping"),
	_SKILL_NURSING ("skillNursing"),
	_SKILL_COMPAGNY ("skillCompagny"),
	_SKILL_ADMINISTRATIVE ("skillAdministrative"),
	_SKILL_DOITYOURSELF ("skillDoityourself"),
	;

	private String _name;

	private ESkills(String name) {
		_name = name;
	}

	public String getName() {
		return _name;
	}

	public static ESkills getByName(String name) {
		for (ESkills value: ESkills.values()) {
			if (value.getName().equals(name)) {
				return value;
			}
		}
		return null;
	}

}
