package org.ap.auxpro.constants;

/* This class was auto-generated by the JavaWriter */
public enum ESocFunction {

	_M_A_N_D ("MAND"),
	_P_R_E_S_T ("PREST"),
	_B_O_T_H ("BOTH"),
	;

	private String _name;

	private  ESocFunction(String name) {
		_name = name;
	}

	public String getName() {
		return _name;
	}

	public static ESocFunction getByName(String name) {
		for (ESocFunction value: ESocFunction.values()) {
			if (value.getName().equals(name)) {
				return value;
			}
		}
		return null;
	}

}
