package org.ap.auxpro.storage;

import org.bson.Document;
import org.bson.conversions.Bson;
import org.ap.web.storage.Mongo;
import static com.mongodb.client.model.Filters.*;
import org.ap.web.internal.APWebException;
import java.util.List;
import java.util.ArrayList;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.result.DeleteResult;

/* This class was auto-generated by the JavaWriter */
public class ApauthCollection {

	public static MongoCollection<Document> getCollection() throws APWebException {
		return Mongo.get().collection("apauth");
	}

	public static ApauthData getByEntityId(String entityId) throws APWebException {
		Document document = getCollection().find(eq("entityId", entityId)).first();
		return fromDocument(document);
	}

	public static boolean deleteByEntityId(String entityId) throws APWebException {
		Document document = getCollection().findOneAndDelete(eq("entityId", entityId));
		return document != null;
	}

	public static ApauthData getById(String id) throws APWebException {
		Document document = getCollection().find(eq("id", id)).first();
		return fromDocument(document);
	}

	public static boolean deleteById(String id) throws APWebException {
		Document document = getCollection().findOneAndDelete(eq("id", id));
		return document != null;
	}

	public static ApauthData getByEmail(String email) throws APWebException {
		Document document = getCollection().find(eq("email", email)).first();
		return fromDocument(document);
	}

	public static boolean deleteByEmail(String email) throws APWebException {
		Document document = getCollection().findOneAndDelete(eq("email", email));
		return document != null;
	}

	public static ApauthData getByUsername(String username) throws APWebException {
		Document document = getCollection().find(eq("username", username)).first();
		return fromDocument(document);
	}

	public static boolean deleteByUsername(String username) throws APWebException {
		Document document = getCollection().findOneAndDelete(eq("username", username));
		return document != null;
	}

	public static List<ApauthData> getAll() throws APWebException {
		FindIterable<Document> documents = getCollection().find();
		List<ApauthData> result = new ArrayList<ApauthData>();
		for (Document document: documents){
			result.add(fromDocument(document));
		}
		return result;
	}

	public static List<ApauthData> get(Bson condition) throws APWebException {
		FindIterable<Document> documents = getCollection().find(condition);
		List<ApauthData> result = new ArrayList<ApauthData>();
		for (Document document: documents){
			result.add(fromDocument(document));
		}
		return result;
	}

	public static void create(ApauthData data) throws APWebException {
		Document document = toDocument(data);
		getCollection().insertOne(document);
	}

	public static boolean update(ApauthData data) throws APWebException {
		Document document = toDocument(data);
		Document result = getCollection().findOneAndUpdate(eq("id", data.getId()), new Document("$set", document));
		return result != null;
	}

	public static boolean updateNull(ApauthData data) throws APWebException {
		Document document = toNullDocument(data);
		Document result = getCollection().findOneAndUpdate(eq("id", data.getId()), new Document("$set", document));
		return result != null;
	}

	public static boolean delete(ApauthData data) throws APWebException {
		Document result = getCollection().findOneAndDelete(eq("id", data.getId()));
		return result != null;
	}

	public static long deleteMany(Bson condition) throws APWebException {
		DeleteResult result = getCollection().deleteMany(condition);
		return result.getDeletedCount();
	}

	public static long drop() throws APWebException {
		long result = getCollection().count();
		getCollection().drop();
		return result;
	}

	@SuppressWarnings("unchecked")
	public static ApauthData fromDocument(Document document) {
		if(document == null) {
			return null;
		}
		ApauthData data = new ApauthData();
		data.tokenData = document.getString("tokenData");
		data.roles = (List<String>)document.get("roles");
		data.tokenDateTime = (List<Integer>)document.get("tokenDateTime");
		data.registered = document.getBoolean("registered");
		data.active = document.getBoolean("active");
		data.entityId = document.getString("entityId");
		data.type = document.getString("type");
		data.token = document.getString("token");
		data.password = document.getString("password");
		data.registrationDate = document.getDate("registrationDate");
		data.id = document.getString("id");
		data.tokenType = document.getString("tokenType");
		data.email = document.getString("email");
		data.username = document.getString("username");
		return data;
	}

	public static Document toDocument(ApauthData apauth) {
		Document document = new Document();
		if (apauth.tokenData != null)
			document.append("tokenData", apauth.tokenData);
		if (apauth.roles != null)
			document.append("roles", apauth.roles);
		if (apauth.tokenDateTime != null)
			document.append("tokenDateTime", apauth.tokenDateTime);
		if (apauth.registered != null)
			document.append("registered", apauth.registered);
		if (apauth.active != null)
			document.append("active", apauth.active);
		if (apauth.entityId != null)
			document.append("entityId", apauth.entityId);
		if (apauth.type != null)
			document.append("type", apauth.type);
		if (apauth.token != null)
			document.append("token", apauth.token);
		if (apauth.password != null)
			document.append("password", apauth.password);
		if (apauth.registrationDate != null)
			document.append("registrationDate", apauth.registrationDate);
		if (apauth.id != null)
			document.append("id", apauth.id);
		if (apauth.tokenType != null)
			document.append("tokenType", apauth.tokenType);
		if (apauth.email != null)
			document.append("email", apauth.email);
		if (apauth.username != null)
			document.append("username", apauth.username);
		return document;
	}

	public static Document toNullDocument(ApauthData apauth) {
		Document document = new Document();
		document.append("tokenData", apauth.tokenData);
		document.append("roles", apauth.roles);
		document.append("tokenDateTime", apauth.tokenDateTime);
		document.append("registered", apauth.registered);
		document.append("active", apauth.active);
		document.append("entityId", apauth.entityId);
		document.append("type", apauth.type);
		document.append("token", apauth.token);
		document.append("password", apauth.password);
		document.append("registrationDate", apauth.registrationDate);
		document.append("id", apauth.id);
		document.append("tokenType", apauth.tokenType);
		document.append("email", apauth.email);
		document.append("username", apauth.username);
		return document;
	}

}
