package org.ap.auxpro.storage;

import java.util.List;

/* This class was auto-generated by the JavaWriter */
public class AuxiliaryData {

	public String authId;
	public String country;
	public String lastName;
	public String civility;
	public String city;
	public List<Integer> lastUpdateDate;
	public String postalCode;
	public Boolean isTutoSkipped;
	public String description;
	public String socialNumber;
	public List<Integer> accountExpiryDate;
	public Integer profilProgression;
	public Integer skillShopping;
	public Boolean notifyOffersSms;
	public Boolean notifyAuxpros;
	public String birthCountry;
	public Boolean profilCompleted;
	public Boolean addressChecked;
	public List<String> diploma;
	public Integer skillDoityourself;
	public String id;
	public String email;
	public Double longitude;
	public Integer skillNursing;
	public String address;
	public Double lattitude;
	public String accountType;
	public Boolean notifyPartners;
	public String birthCity;
	public String avatar;
	public Boolean areSkillSet;
	public List<Integer> creationDate;
	public List<Integer> birthDate;
	public Integer skillChildhood;
	public Integer skillCompagny;
	public String firstName;
	public List<Integer> skillAnswers;
	public String nationality;
	public String isEntrepreneur;
	public String phone;
	public Integer skillAdministrative;
	public Boolean phoneChecked;
	public Integer skillHousework;
	public String idCardNumber;
	public Boolean emailChecked;
	public Boolean notifyOffersMail;

	public String getAuthId() {
		return this.authId;
	}

	public void setAuthId(String authId) {
		this.authId = authId;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getCivility() {
		return this.civility;
	}

	public void setCivility(String civility) {
		this.civility = civility;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public List<Integer> getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(List<Integer> lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public Boolean getIsTutoSkipped() {
		return this.isTutoSkipped;
	}

	public void setIsTutoSkipped(Boolean isTutoSkipped) {
		this.isTutoSkipped = isTutoSkipped;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSocialNumber() {
		return this.socialNumber;
	}

	public void setSocialNumber(String socialNumber) {
		this.socialNumber = socialNumber;
	}

	public List<Integer> getAccountExpiryDate() {
		return this.accountExpiryDate;
	}

	public void setAccountExpiryDate(List<Integer> accountExpiryDate) {
		this.accountExpiryDate = accountExpiryDate;
	}

	public Integer getProfilProgression() {
		return this.profilProgression;
	}

	public void setProfilProgression(Integer profilProgression) {
		this.profilProgression = profilProgression;
	}

	public Integer getSkillShopping() {
		return this.skillShopping;
	}

	public void setSkillShopping(Integer skillShopping) {
		this.skillShopping = skillShopping;
	}

	public Boolean getNotifyOffersSms() {
		return this.notifyOffersSms;
	}

	public void setNotifyOffersSms(Boolean notifyOffersSms) {
		this.notifyOffersSms = notifyOffersSms;
	}

	public Boolean getNotifyAuxpros() {
		return this.notifyAuxpros;
	}

	public void setNotifyAuxpros(Boolean notifyAuxpros) {
		this.notifyAuxpros = notifyAuxpros;
	}

	public String getBirthCountry() {
		return this.birthCountry;
	}

	public void setBirthCountry(String birthCountry) {
		this.birthCountry = birthCountry;
	}

	public Boolean getProfilCompleted() {
		return this.profilCompleted;
	}

	public void setProfilCompleted(Boolean profilCompleted) {
		this.profilCompleted = profilCompleted;
	}

	public Boolean getAddressChecked() {
		return this.addressChecked;
	}

	public void setAddressChecked(Boolean addressChecked) {
		this.addressChecked = addressChecked;
	}

	public List<String> getDiploma() {
		return this.diploma;
	}

	public void setDiploma(List<String> diploma) {
		this.diploma = diploma;
	}

	public Integer getSkillDoityourself() {
		return this.skillDoityourself;
	}

	public void setSkillDoityourself(Integer skillDoityourself) {
		this.skillDoityourself = skillDoityourself;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Integer getSkillNursing() {
		return this.skillNursing;
	}

	public void setSkillNursing(Integer skillNursing) {
		this.skillNursing = skillNursing;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Double getLattitude() {
		return this.lattitude;
	}

	public void setLattitude(Double lattitude) {
		this.lattitude = lattitude;
	}

	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	public Boolean getNotifyPartners() {
		return this.notifyPartners;
	}

	public void setNotifyPartners(Boolean notifyPartners) {
		this.notifyPartners = notifyPartners;
	}

	public String getBirthCity() {
		return this.birthCity;
	}

	public void setBirthCity(String birthCity) {
		this.birthCity = birthCity;
	}

	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public Boolean getAreSkillSet() {
		return this.areSkillSet;
	}

	public void setAreSkillSet(Boolean areSkillSet) {
		this.areSkillSet = areSkillSet;
	}

	public List<Integer> getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(List<Integer> creationDate) {
		this.creationDate = creationDate;
	}

	public List<Integer> getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(List<Integer> birthDate) {
		this.birthDate = birthDate;
	}

	public Integer getSkillChildhood() {
		return this.skillChildhood;
	}

	public void setSkillChildhood(Integer skillChildhood) {
		this.skillChildhood = skillChildhood;
	}

	public Integer getSkillCompagny() {
		return this.skillCompagny;
	}

	public void setSkillCompagny(Integer skillCompagny) {
		this.skillCompagny = skillCompagny;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public List<Integer> getSkillAnswers() {
		return this.skillAnswers;
	}

	public void setSkillAnswers(List<Integer> skillAnswers) {
		this.skillAnswers = skillAnswers;
	}

	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public String getIsEntrepreneur() {
		return this.isEntrepreneur;
	}

	public void setIsEntrepreneur(String isEntrepreneur) {
		this.isEntrepreneur = isEntrepreneur;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Integer getSkillAdministrative() {
		return this.skillAdministrative;
	}

	public void setSkillAdministrative(Integer skillAdministrative) {
		this.skillAdministrative = skillAdministrative;
	}

	public Boolean getPhoneChecked() {
		return this.phoneChecked;
	}

	public void setPhoneChecked(Boolean phoneChecked) {
		this.phoneChecked = phoneChecked;
	}

	public Integer getSkillHousework() {
		return this.skillHousework;
	}

	public void setSkillHousework(Integer skillHousework) {
		this.skillHousework = skillHousework;
	}

	public String getIdCardNumber() {
		return this.idCardNumber;
	}

	public void setIdCardNumber(String idCardNumber) {
		this.idCardNumber = idCardNumber;
	}

	public Boolean getEmailChecked() {
		return this.emailChecked;
	}

	public void setEmailChecked(Boolean emailChecked) {
		this.emailChecked = emailChecked;
	}

	public Boolean getNotifyOffersMail() {
		return this.notifyOffersMail;
	}

	public void setNotifyOffersMail(Boolean notifyOffersMail) {
		this.notifyOffersMail = notifyOffersMail;
	}

}
