package org.ap.auxpro.storage;

import java.util.List;

/* This class was auto-generated by the JavaWriter */
public class CustomerData {

	public String lastName;
	public String country;
	public String civility;
	public String address;
	public Integer skillNursing;
	public String city;
	public Double lattitude;
	public Integer postalCode;
	public List<Integer> birthDate;
	public Integer skillChildhood;
	public Integer skillCompagny;
	public Integer skillShopping;
	public String firstName;
	public String nationality;
	public String phone;
	public Integer skillAdministrative;
	public Integer skillHousework;
	public Integer skillDoityourself;
	public String id;
	public String serviceId;
	public String email;
	public Double longitude;

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCivility() {
		return this.civility;
	}

	public void setCivility(String civility) {
		this.civility = civility;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getSkillNursing() {
		return this.skillNursing;
	}

	public void setSkillNursing(Integer skillNursing) {
		this.skillNursing = skillNursing;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Double getLattitude() {
		return this.lattitude;
	}

	public void setLattitude(Double lattitude) {
		this.lattitude = lattitude;
	}

	public Integer getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(Integer postalCode) {
		this.postalCode = postalCode;
	}

	public List<Integer> getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(List<Integer> birthDate) {
		this.birthDate = birthDate;
	}

	public Integer getSkillChildhood() {
		return this.skillChildhood;
	}

	public void setSkillChildhood(Integer skillChildhood) {
		this.skillChildhood = skillChildhood;
	}

	public Integer getSkillCompagny() {
		return this.skillCompagny;
	}

	public void setSkillCompagny(Integer skillCompagny) {
		this.skillCompagny = skillCompagny;
	}

	public Integer getSkillShopping() {
		return this.skillShopping;
	}

	public void setSkillShopping(Integer skillShopping) {
		this.skillShopping = skillShopping;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Integer getSkillAdministrative() {
		return this.skillAdministrative;
	}

	public void setSkillAdministrative(Integer skillAdministrative) {
		this.skillAdministrative = skillAdministrative;
	}

	public Integer getSkillHousework() {
		return this.skillHousework;
	}

	public void setSkillHousework(Integer skillHousework) {
		this.skillHousework = skillHousework;
	}

	public Integer getSkillDoityourself() {
		return this.skillDoityourself;
	}

	public void setSkillDoityourself(Integer skillDoityourself) {
		this.skillDoityourself = skillDoityourself;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(String serviceId) {
		this.serviceId = serviceId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

}
