package org.ap.auxpro.storage;

import java.util.List;

/* This class was auto-generated by the JavaWriter */
public class GeozoneData {

	public String auxiliaryId;
	public String address;
	public Double lattitude;
	public String city;
	public List<Integer> lastUpdateDate;
	public String postalCode;
	public String id;
	public String type;
	public Integer radius;
	public List<Integer> creationDate;
	public Double longitude;

	public String getAuxiliaryId() {
		return this.auxiliaryId;
	}

	public void setAuxiliaryId(String auxiliaryId) {
		this.auxiliaryId = auxiliaryId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Double getLattitude() {
		return this.lattitude;
	}

	public void setLattitude(Double lattitude) {
		this.lattitude = lattitude;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public List<Integer> getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(List<Integer> lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getRadius() {
		return this.radius;
	}

	public void setRadius(Integer radius) {
		this.radius = radius;
	}

	public List<Integer> getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(List<Integer> creationDate) {
		this.creationDate = creationDate;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

}
