package org.ap.auxpro.storage;

import org.ap.common.validators.EValidators;
import org.ap.common.validators.IValidator;

/* This class was auto-generated by the JavaWriter */
public enum GeozoneFields {

	AUXILIARY_ID (EValidators.DEFAULT.getValidator()),
	ADDRESS (EValidators.DEFAULT.getValidator()),
	LATTITUDE (EValidators.DEFAULT.getValidator()),
	CITY (EValidators.DEFAULT.getValidator()),
	POSTAL_CODE (EValidators.DEFAULT.getValidator()),
	ID (EValidators.DEFAULT.getValidator()),
	TYPE (EValidators.DEFAULT.getValidator()),
	RADIUS (EValidators.DEFAULT.getValidator()),
	LONGITUDE (EValidators.DEFAULT.getValidator()),
	;

	private IValidator<?> _validator;

	private  GeozoneFields(IValidator<?> validator) {
		_validator = validator;
	}

	public IValidator<?> getValidator() {
		return _validator;
	}

}
