package org.ap.auxpro.storage;

import org.ap.common.validators.EValidators;
import org.ap.common.validators.IValidator;

/* This class was auto-generated by the JavaWriter */
public enum HelpfaqFields {

	ID (EValidators.DEFAULT.getValidator()),
	TITLE (EValidators.DEFAULT.getValidator()),
	CONTENT (EValidators.DEFAULT.getValidator()),
	;

	private IValidator<?> _validator;

	private  HelpfaqFields(IValidator<?> validator) {
		_validator = validator;
	}

	public IValidator<?> getValidator() {
		return _validator;
	}

}
