package org.ap.auxpro.storage;

import java.util.List;

/* This class was auto-generated by the JavaWriter */
public class IndisponibilityData {

	public String period;
	public String auxiliaryId;
	public List<Integer> endDate;
	public List<String> days;
	public List<Integer> startTime;
	public List<Integer> endTime;
	public String id;
	public List<Integer> startDate;

	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public String getAuxiliaryId() {
		return this.auxiliaryId;
	}

	public void setAuxiliaryId(String auxiliaryId) {
		this.auxiliaryId = auxiliaryId;
	}

	public List<Integer> getEndDate() {
		return this.endDate;
	}

	public void setEndDate(List<Integer> endDate) {
		this.endDate = endDate;
	}

	public List<String> getDays() {
		return this.days;
	}

	public void setDays(List<String> days) {
		this.days = days;
	}

	public List<Integer> getStartTime() {
		return this.startTime;
	}

	public void setStartTime(List<Integer> startTime) {
		this.startTime = startTime;
	}

	public List<Integer> getEndTime() {
		return this.endTime;
	}

	public void setEndTime(List<Integer> endTime) {
		this.endTime = endTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public List<Integer> getStartDate() {
		return this.startDate;
	}

	public void setStartDate(List<Integer> startDate) {
		this.startDate = startDate;
	}

}
