package org.ap.auxpro.storage;

import org.bson.Document;
import org.bson.conversions.Bson;
import org.ap.web.storage.Mongo;
import static com.mongodb.client.model.Filters.*;
import org.ap.web.internal.APWebException;
import java.util.List;
import java.util.ArrayList;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.result.DeleteResult;

/* This class was auto-generated by the JavaWriter */
public class IndisponibilityCollection {

	public static MongoCollection<Document> getCollection() throws APWebException {
		return Mongo.get().collection("indisponibility");
	}

	public static IndisponibilityData getById(String id) throws APWebException {
		Document document = getCollection().find(eq("id", id)).first();
		return fromDocument(document);
	}

	public static boolean deleteById(String id) throws APWebException {
		Document document = getCollection().findOneAndDelete(eq("id", id));
		return document != null;
	}

	public static List<IndisponibilityData> getAll() throws APWebException {
		FindIterable<Document> documents = getCollection().find();
		List<IndisponibilityData> result = new ArrayList<IndisponibilityData>();
		for (Document document: documents){
			result.add(fromDocument(document));
		}
		return result;
	}

	public static List<IndisponibilityData> get(Bson condition) throws APWebException {
		FindIterable<Document> documents = getCollection().find(condition);
		List<IndisponibilityData> result = new ArrayList<IndisponibilityData>();
		for (Document document: documents){
			result.add(fromDocument(document));
		}
		return result;
	}

	public static void create(IndisponibilityData data) throws APWebException {
		Document document = toDocument(data);
		getCollection().insertOne(document);
	}

	public static boolean update(IndisponibilityData data) throws APWebException {
		Document document = toDocument(data);
		Document result = getCollection().findOneAndUpdate(eq("id", data.getId()), new Document("$set", document));
		return result != null;
	}

	public static boolean updateNull(IndisponibilityData data) throws APWebException {
		Document document = toNullDocument(data);
		Document result = getCollection().findOneAndUpdate(eq("id", data.getId()), new Document("$set", document));
		return result != null;
	}

	public static boolean delete(IndisponibilityData data) throws APWebException {
		Document result = getCollection().findOneAndDelete(eq("id", data.getId()));
		return result != null;
	}

	public static long deleteMany(Bson condition) throws APWebException {
		DeleteResult result = getCollection().deleteMany(condition);
		return result.getDeletedCount();
	}

	public static long drop() throws APWebException {
		long result = getCollection().count();
		getCollection().drop();
		return result;
	}

	@SuppressWarnings("unchecked")
	public static IndisponibilityData fromDocument(Document document) {
		if(document == null) {
			return null;
		}
		IndisponibilityData data = new IndisponibilityData();
		data.period = document.getString("period");
		data.auxiliaryId = document.getString("auxiliaryId");
		data.endDate = (List<Integer>)document.get("endDate");
		data.days = (List<String>)document.get("days");
		data.startTime = (List<Integer>)document.get("startTime");
		data.endTime = (List<Integer>)document.get("endTime");
		data.id = document.getString("id");
		data.startDate = (List<Integer>)document.get("startDate");
		return data;
	}

	public static Document toDocument(IndisponibilityData indisponibility) {
		Document document = new Document();
		if (indisponibility.period != null)
			document.append("period", indisponibility.period);
		if (indisponibility.auxiliaryId != null)
			document.append("auxiliaryId", indisponibility.auxiliaryId);
		if (indisponibility.endDate != null)
			document.append("endDate", indisponibility.endDate);
		if (indisponibility.days != null)
			document.append("days", indisponibility.days);
		if (indisponibility.startTime != null)
			document.append("startTime", indisponibility.startTime);
		if (indisponibility.endTime != null)
			document.append("endTime", indisponibility.endTime);
		if (indisponibility.id != null)
			document.append("id", indisponibility.id);
		if (indisponibility.startDate != null)
			document.append("startDate", indisponibility.startDate);
		return document;
	}

	public static Document toNullDocument(IndisponibilityData indisponibility) {
		Document document = new Document();
		document.append("period", indisponibility.period);
		document.append("auxiliaryId", indisponibility.auxiliaryId);
		document.append("endDate", indisponibility.endDate);
		document.append("days", indisponibility.days);
		document.append("startTime", indisponibility.startTime);
		document.append("endTime", indisponibility.endTime);
		document.append("id", indisponibility.id);
		document.append("startDate", indisponibility.startDate);
		return document;
	}

}
