package org.ap.auxpro.storage;

import java.util.List;

/* This class was auto-generated by the JavaWriter */
public class InterventionData {

	public String period;
	public String auxiliaryId;
	public List<Integer> endDate;
	public List<Integer> lastUpdateDate;
	public List<Integer> sadStatusChanged;
	public List<Integer> creationDate;
	public String customerId;
	public List<String> days;
	public String sadStatus;
	public List<Integer> startTime;
	public String id;
	public List<Integer> endTime;
	public String serviceId;
	public Boolean hideToSad;
	public List<Integer> startDate;

	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public String getAuxiliaryId() {
		return this.auxiliaryId;
	}

	public void setAuxiliaryId(String auxiliaryId) {
		this.auxiliaryId = auxiliaryId;
	}

	public List<Integer> getEndDate() {
		return this.endDate;
	}

	public void setEndDate(List<Integer> endDate) {
		this.endDate = endDate;
	}

	public List<Integer> getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(List<Integer> lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public List<Integer> getSadStatusChanged() {
		return this.sadStatusChanged;
	}

	public void setSadStatusChanged(List<Integer> sadStatusChanged) {
		this.sadStatusChanged = sadStatusChanged;
	}

	public List<Integer> getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(List<Integer> creationDate) {
		this.creationDate = creationDate;
	}

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public List<String> getDays() {
		return this.days;
	}

	public void setDays(List<String> days) {
		this.days = days;
	}

	public String getSadStatus() {
		return this.sadStatus;
	}

	public void setSadStatus(String sadStatus) {
		this.sadStatus = sadStatus;
	}

	public List<Integer> getStartTime() {
		return this.startTime;
	}

	public void setStartTime(List<Integer> startTime) {
		this.startTime = startTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public List<Integer> getEndTime() {
		return this.endTime;
	}

	public void setEndTime(List<Integer> endTime) {
		this.endTime = endTime;
	}

	public String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(String serviceId) {
		this.serviceId = serviceId;
	}

	public Boolean getHideToSad() {
		return this.hideToSad;
	}

	public void setHideToSad(Boolean hideToSad) {
		this.hideToSad = hideToSad;
	}

	public List<Integer> getStartDate() {
		return this.startDate;
	}

	public void setStartDate(List<Integer> startDate) {
		this.startDate = startDate;
	}

}
