import React from 'react'
import ServiceInfosEditSocietyData from 'components/service/infos/edit/society/ServiceInfosEditSocietyData'
import './ServiceInfosEditSociety.scss'

/* This class was auto-generated by the JavaScriptWriter */
class ServiceInfosEditSociety extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		ServiceInfosEditSocietyData.register(this)
	}

	componentWillUnmount() {
		ServiceInfosEditSocietyData.unregister()
	}

	render() {
		return (
			<div className='ap-serviceinfoseditsociety'>
				ServiceInfosEditSociety
			</div>
		)
	}

}
export default ServiceInfosEditSociety
