import React from 'react'
import ServicesData from 'components/infos/services/ServicesData'
import './Services.scss'

/* This class was auto-generated by the JavaScriptWriter */
class Services extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		ServicesData.register(this)
	}

	componentWillUnmount() {
		ServicesData.unregister()
	}

	render() {
		return (
			<div className='ap-services'>
				Services
			</div>
		)
	}

}
export default Services
