import React from 'react'
import AuxiliaryInfosQuestionaryData from 'components/auxiliary/infos/questionary/AuxiliaryInfosQuestionaryData'
import './AuxiliaryInfosQuestionary.scss'

/* This class was auto-generated by the JavaScriptWriter */
class AuxiliaryInfosQuestionary extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		AuxiliaryInfosQuestionaryData.register(this)
	}

	componentWillUnmount() {
		AuxiliaryInfosQuestionaryData.unregister()
	}

	render() {
		return (
			<div className='ap-auxiliaryinfosquestionary'>
				AuxiliaryInfosQuestionary
			</div>
		)
	}

}
export default AuxiliaryInfosQuestionary
