package org.ap.auxpro.storage.auxiliary;

import org.ap.common.storage.IFieldEnum;
import org.ap.common.validators.ValidatorProvider;
import org.ap.auxpro.internal.Validators;

/* This class was auto-generated by the JavaWriter */
public enum AuxiliaryFields implements IFieldEnum {

	COUNTRY ("country", "String", new Validators.NON_EMPTY_STRING()),
	LAST_NAME ("lastName", "String", new Validators.NON_EMPTY_STRING()),
	CIVILITY ("civility", "String", new Validators.NON_NULL()),
	CITY ("city", "String", new Validators.NON_EMPTY_STRING()),
	LAST_UPDATE_DATE ("lastUpdateDate", "List<Integer>", new Validators.DEFAULT()),
	POSTAL_CODE ("postalCode", "String", new Validators.POSTAL_CODE()),
	IS_TUTO_SKIPPED ("isTutoSkipped", "Boolean", new Validators.DEFAULT()),
	DESCRIPTION ("description", "String", new Validators.TWEET()),
	SOCIAL_NUMBER ("socialNumber", "String", new Validators.SOCIAL_NUMBER()),
	ACCOUNT_EXPIRY_DATE ("accountExpiryDate", "List<Integer>", new Validators.DEFAULT()),
	PROFIL_PROGRESSION ("profilProgression", "Integer", new Validators.DEFAULT()),
	SKILL_SHOPPING ("skillShopping", "Integer", new Validators.DEFAULT()),
	NOTIFY_OFFERS_SMS ("notifyOffersSms", "Boolean", new Validators.DEFAULT()),
	NOTIFY_AUXPROS ("notifyAuxpros", "Boolean", new Validators.DEFAULT()),
	BIRTH_COUNTRY ("birthCountry", "String", new Validators.NON_EMPTY_STRING()),
	PROFIL_COMPLETED ("profilCompleted", "Boolean", new Validators.DEFAULT()),
	ID ("id", "String", new Validators.DEFAULT()),
	DIPLOMA ("diploma", "String", new Validators.NON_EMPTY_ARRAY()),
	SKILL_DOITYOURSELF ("skillDoityourself", "Integer", new Validators.DEFAULT()),
	LONGITUDE ("longitude", "Double", new Validators.DEFAULT()),
	ADDRESS ("address", "String", new Validators.NON_EMPTY_STRING()),
	SKILL_NURSING ("skillNursing", "Integer", new Validators.DEFAULT()),
	LATTITUDE ("lattitude", "Double", new Validators.DEFAULT()),
	ACCOUNT_TYPE ("accountType", "String", new Validators.DEFAULT()),
	NOTIFY_PARTNERS ("notifyPartners", "Boolean", new Validators.DEFAULT()),
	BIRTH_CITY ("birthCity", "String", new Validators.NON_EMPTY_STRING()),
	AVATAR ("avatar", "String", new Validators.DEFAULT()),
	CREATION_DATE ("creationDate", "List<Integer>", new Validators.DEFAULT()),
	ARE_SKILL_SET ("areSkillSet", "Boolean", new Validators.DEFAULT()),
	BIRTH_DATE ("birthDate", "List<Integer>", new Validators.BEFORE_TODAY()),
	SKILL_CHILDHOOD ("skillChildhood", "Integer", new Validators.DEFAULT()),
	SKILL_COMPAGNY ("skillCompagny", "Integer", new Validators.DEFAULT()),
	FIRST_NAME ("firstName", "String", new Validators.NON_EMPTY_STRING()),
	SKILL_ANSWERS ("skillAnswers", "Integer", new Validators.DEFAULT()),
	NATIONALITY ("nationality", "String", new Validators.NON_NULL()),
	IS_ENTREPRENEUR ("isEntrepreneur", "String", new Validators.NON_NULL()),
	PHONE ("phone", "String", new Validators.PHONE()),
	SKILL_ADMINISTRATIVE ("skillAdministrative", "Integer", new Validators.DEFAULT()),
	SKILL_HOUSEWORK ("skillHousework", "Integer", new Validators.DEFAULT()),
	NOTIFY_OFFERS_MAIL ("notifyOffersMail", "Boolean", new Validators.DEFAULT()),
	;

	private String _id;
	private String _type;
	private ValidatorProvider _validator;

	private AuxiliaryFields(String id, String type, ValidatorProvider validator) {
		_id = id;
		_type = type;
		_validator = validator;
	}

	public String getId() {
		return _id;
	}

	public String getType() {
		return _type;
	}

	public ValidatorProvider getValidator() {
		return _validator;
	}

	public static AuxiliaryFields byId(String id) {
		for (AuxiliaryFields value : AuxiliaryFields.values()) {
			if (value.getId().equals(id)) {
				return value;
			}
		}
		return null;
	}

}
