package org.ap.auxpro.storage.auxiliary;

import org.bson.Document;
import org.bson.conversions.Bson;
import org.ap.web.storage.Mongo;
import static com.mongodb.client.model.Filters.*;
import org.ap.web.internal.APWebException;
import java.util.List;
import java.util.ArrayList;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.result.DeleteResult;

/* This class was auto-generated by the JavaWriter */
public class AuxiliaryCollection {

	public static MongoCollection<Document> getCollection() throws APWebException {
		return Mongo.get().collection("auxiliary");
	}

	public static AuxiliaryData getByAuthId(String authId) throws APWebException {
		Document document = getCollection().find(eq("authId", authId)).first();
		return fromDocument(document);
	}

	public static boolean deleteByAuthId(String authId) throws APWebException {
		Document document = getCollection().findOneAndDelete(eq("authId", authId));
		return document != null;
	}

	public static AuxiliaryData getById(String id) throws APWebException {
		Document document = getCollection().find(eq("id", id)).first();
		return fromDocument(document);
	}

	public static boolean deleteById(String id) throws APWebException {
		Document document = getCollection().findOneAndDelete(eq("id", id));
		return document != null;
	}

	public static List<AuxiliaryData> getAll() throws APWebException {
		FindIterable<Document> documents = getCollection().find();
		List<AuxiliaryData> result = new ArrayList<AuxiliaryData>();
		for (Document document: documents){
			result.add(fromDocument(document));
		}
		return result;
	}

	public static List<AuxiliaryData> get(Bson condition) throws APWebException {
		FindIterable<Document> documents = getCollection().find(condition);
		List<AuxiliaryData> result = new ArrayList<AuxiliaryData>();
		for (Document document: documents){
			result.add(fromDocument(document));
		}
		return result;
	}

	public static void create(AuxiliaryData data) throws APWebException {
		Document document = toDocument(data);
		getCollection().insertOne(document);
	}

	public static boolean update(AuxiliaryData data) throws APWebException {
		Document document = toDocument(data);
		Document result = getCollection().findOneAndUpdate(eq("id", data.getId()), new Document("$set", document));
		return result != null;
	}

	public static boolean updateNull(AuxiliaryData data) throws APWebException {
		Document document = toNullDocument(data);
		Document result = getCollection().findOneAndUpdate(eq("id", data.getId()), new Document("$set", document));
		return result != null;
	}

	public static boolean delete(AuxiliaryData data) throws APWebException {
		Document result = getCollection().findOneAndDelete(eq("id", data.getId()));
		return result != null;
	}

	public static long deleteMany(Bson condition) throws APWebException {
		DeleteResult result = getCollection().deleteMany(condition);
		return result.getDeletedCount();
	}

	public static long drop() throws APWebException {
		long result = getCollection().count();
		getCollection().drop();
		return result;
	}

	@SuppressWarnings("unchecked")
	public static AuxiliaryData fromDocument(Document document) {
		if(document == null) {
			return null;
		}
		AuxiliaryData data = new AuxiliaryData();
		data.authId = document.getString("authId");
		data.country = document.getString("country");
		data.lastName = document.getString("lastName");
		data.civility = document.getString("civility");
		data.city = document.getString("city");
		data.lastUpdateDate = document.getDate("lastUpdateDate");
		data.postalCode = document.getString("postalCode");
		data.isTutoSkipped = document.getBoolean("isTutoSkipped");
		data.description = document.getString("description");
		data.socialNumber = document.getString("socialNumber");
		data.accountExpiryDate = document.getDate("accountExpiryDate");
		data.profilProgression = document.getInteger("profilProgression");
		data.skillShopping = document.getInteger("skillShopping");
		data.notifyOffersSms = document.getBoolean("notifyOffersSms");
		data.notifyAuxpros = document.getBoolean("notifyAuxpros");
		data.birthCountry = document.getString("birthCountry");
		data.profilCompleted = document.getBoolean("profilCompleted");
		data.id = document.getString("id");
		data.diploma = (List<String>)document.get("diploma");
		data.skillDoityourself = document.getInteger("skillDoityourself");
		data.longitude = document.getDouble("longitude");
		data.address = document.getString("address");
		data.skillNursing = document.getInteger("skillNursing");
		data.lattitude = document.getDouble("lattitude");
		data.accountType = document.getString("accountType");
		data.notifyPartners = document.getBoolean("notifyPartners");
		data.birthCity = document.getString("birthCity");
		data.avatar = document.getString("avatar");
		data.creationDate = document.getDate("creationDate");
		data.areSkillSet = document.getBoolean("areSkillSet");
		data.birthDate = document.getDate("birthDate");
		data.skillChildhood = document.getInteger("skillChildhood");
		data.skillCompagny = document.getInteger("skillCompagny");
		data.firstName = document.getString("firstName");
		data.skillAnswers = (List<Integer>)document.get("skillAnswers");
		data.nationality = document.getString("nationality");
		data.isEntrepreneur = document.getString("isEntrepreneur");
		data.phone = document.getString("phone");
		data.skillAdministrative = document.getInteger("skillAdministrative");
		data.skillHousework = document.getInteger("skillHousework");
		data.notifyOffersMail = document.getBoolean("notifyOffersMail");
		return data;
	}

	public static Document toDocument(AuxiliaryData auxiliary) {
		Document document = new Document();
		if (auxiliary.authId != null)
			document.append("authId", auxiliary.authId);
		if (auxiliary.country != null)
			document.append("country", auxiliary.country);
		if (auxiliary.lastName != null)
			document.append("lastName", auxiliary.lastName);
		if (auxiliary.civility != null)
			document.append("civility", auxiliary.civility);
		if (auxiliary.city != null)
			document.append("city", auxiliary.city);
		if (auxiliary.lastUpdateDate != null)
			document.append("lastUpdateDate", auxiliary.lastUpdateDate);
		if (auxiliary.postalCode != null)
			document.append("postalCode", auxiliary.postalCode);
		if (auxiliary.isTutoSkipped != null)
			document.append("isTutoSkipped", auxiliary.isTutoSkipped);
		if (auxiliary.description != null)
			document.append("description", auxiliary.description);
		if (auxiliary.socialNumber != null)
			document.append("socialNumber", auxiliary.socialNumber);
		if (auxiliary.accountExpiryDate != null)
			document.append("accountExpiryDate", auxiliary.accountExpiryDate);
		if (auxiliary.profilProgression != null)
			document.append("profilProgression", auxiliary.profilProgression);
		if (auxiliary.skillShopping != null)
			document.append("skillShopping", auxiliary.skillShopping);
		if (auxiliary.notifyOffersSms != null)
			document.append("notifyOffersSms", auxiliary.notifyOffersSms);
		if (auxiliary.notifyAuxpros != null)
			document.append("notifyAuxpros", auxiliary.notifyAuxpros);
		if (auxiliary.birthCountry != null)
			document.append("birthCountry", auxiliary.birthCountry);
		if (auxiliary.profilCompleted != null)
			document.append("profilCompleted", auxiliary.profilCompleted);
		if (auxiliary.id != null)
			document.append("id", auxiliary.id);
		if (auxiliary.diploma != null)
			document.append("diploma", auxiliary.diploma);
		if (auxiliary.skillDoityourself != null)
			document.append("skillDoityourself", auxiliary.skillDoityourself);
		if (auxiliary.longitude != null)
			document.append("longitude", auxiliary.longitude);
		if (auxiliary.address != null)
			document.append("address", auxiliary.address);
		if (auxiliary.skillNursing != null)
			document.append("skillNursing", auxiliary.skillNursing);
		if (auxiliary.lattitude != null)
			document.append("lattitude", auxiliary.lattitude);
		if (auxiliary.accountType != null)
			document.append("accountType", auxiliary.accountType);
		if (auxiliary.notifyPartners != null)
			document.append("notifyPartners", auxiliary.notifyPartners);
		if (auxiliary.birthCity != null)
			document.append("birthCity", auxiliary.birthCity);
		if (auxiliary.avatar != null)
			document.append("avatar", auxiliary.avatar);
		if (auxiliary.creationDate != null)
			document.append("creationDate", auxiliary.creationDate);
		if (auxiliary.areSkillSet != null)
			document.append("areSkillSet", auxiliary.areSkillSet);
		if (auxiliary.birthDate != null)
			document.append("birthDate", auxiliary.birthDate);
		if (auxiliary.skillChildhood != null)
			document.append("skillChildhood", auxiliary.skillChildhood);
		if (auxiliary.skillCompagny != null)
			document.append("skillCompagny", auxiliary.skillCompagny);
		if (auxiliary.firstName != null)
			document.append("firstName", auxiliary.firstName);
		if (auxiliary.skillAnswers != null)
			document.append("skillAnswers", auxiliary.skillAnswers);
		if (auxiliary.nationality != null)
			document.append("nationality", auxiliary.nationality);
		if (auxiliary.isEntrepreneur != null)
			document.append("isEntrepreneur", auxiliary.isEntrepreneur);
		if (auxiliary.phone != null)
			document.append("phone", auxiliary.phone);
		if (auxiliary.skillAdministrative != null)
			document.append("skillAdministrative", auxiliary.skillAdministrative);
		if (auxiliary.skillHousework != null)
			document.append("skillHousework", auxiliary.skillHousework);
		if (auxiliary.notifyOffersMail != null)
			document.append("notifyOffersMail", auxiliary.notifyOffersMail);
		return document;
	}

	public static Document toNullDocument(AuxiliaryData auxiliary) {
		Document document = new Document();
		document.append("authId", auxiliary.authId);
		document.append("country", auxiliary.country);
		document.append("lastName", auxiliary.lastName);
		document.append("civility", auxiliary.civility);
		document.append("city", auxiliary.city);
		document.append("lastUpdateDate", auxiliary.lastUpdateDate);
		document.append("postalCode", auxiliary.postalCode);
		document.append("isTutoSkipped", auxiliary.isTutoSkipped);
		document.append("description", auxiliary.description);
		document.append("socialNumber", auxiliary.socialNumber);
		document.append("accountExpiryDate", auxiliary.accountExpiryDate);
		document.append("profilProgression", auxiliary.profilProgression);
		document.append("skillShopping", auxiliary.skillShopping);
		document.append("notifyOffersSms", auxiliary.notifyOffersSms);
		document.append("notifyAuxpros", auxiliary.notifyAuxpros);
		document.append("birthCountry", auxiliary.birthCountry);
		document.append("profilCompleted", auxiliary.profilCompleted);
		document.append("id", auxiliary.id);
		document.append("diploma", auxiliary.diploma);
		document.append("skillDoityourself", auxiliary.skillDoityourself);
		document.append("longitude", auxiliary.longitude);
		document.append("address", auxiliary.address);
		document.append("skillNursing", auxiliary.skillNursing);
		document.append("lattitude", auxiliary.lattitude);
		document.append("accountType", auxiliary.accountType);
		document.append("notifyPartners", auxiliary.notifyPartners);
		document.append("birthCity", auxiliary.birthCity);
		document.append("avatar", auxiliary.avatar);
		document.append("creationDate", auxiliary.creationDate);
		document.append("areSkillSet", auxiliary.areSkillSet);
		document.append("birthDate", auxiliary.birthDate);
		document.append("skillChildhood", auxiliary.skillChildhood);
		document.append("skillCompagny", auxiliary.skillCompagny);
		document.append("firstName", auxiliary.firstName);
		document.append("skillAnswers", auxiliary.skillAnswers);
		document.append("nationality", auxiliary.nationality);
		document.append("isEntrepreneur", auxiliary.isEntrepreneur);
		document.append("phone", auxiliary.phone);
		document.append("skillAdministrative", auxiliary.skillAdministrative);
		document.append("skillHousework", auxiliary.skillHousework);
		document.append("notifyOffersMail", auxiliary.notifyOffersMail);
		return document;
	}

}
