import React from 'react'
import ServiceZoneData from './ServiceZoneData'
import './ServiceZone.scss'

/* This class was auto-generated by the JavaScriptWriter */
class ServiceZone extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		ServiceZoneData.register(this)
	}

	componentWillUnmount() {
		ServiceZoneData.unregister()
	}

	render() {
		return (
			<div className='ap-servicezone'>
				ServiceZone
			</div>
		)
	}

}
export default ServiceZone
