import React from 'react'
import AppHomeData from 'components/home/AppHomeData'
import './AppHome.scss'

/* This class was auto-generated by the JavaScriptWriter */
class AppHome extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		AppHomeData.register(this)
	}

	componentWillUnmount() {
		AppHomeData.unregister()
	}

	render() {
		return (
			<div className='ap-apphome'>
				AppHome
			</div>
		)
	}

}
export default AppHome
