import AppHelper from 'helpers/AppHelper'
import { BaseData } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class AppHomeData extends BaseData {

	register(obj) {
		super.register(obj)
		
		// Callbacks
		this.obj.onLogon = AppHelper.navigate.bind(AppHelper, '/auth/login')
		this.obj.onRegisterAux = AppHelper.navigate.bind(AppHelper, '/auth/register/auxiliary')
		this.obj.onRegisterSad = AppHelper.navigate.bind(AppHelper, '/auth/register/service')
		this.obj.onNavDGE = this.onNavDGE.bind(this)

		// State
		this.obj.state = {}
	}

	unregister() {
	}

	onNavDGE() {
 		window.open('http://www.entreprises.gouv.fr/services-a-la-personne/annuaire-des-organismes-services-a-la-personne', '_blank').focus()
	}

}
var AppHomeObj = new AppHomeData()
export default AppHomeObj
