package org.ap.auxpro.rest;

import org.ap.auxpro.internal.EConfigProperties;
import org.ap.auxpro.rest.filter.HeadersResponseFilter;
import org.ap.common.mongo.Mongo;
import javax.ws.rs.ApplicationPath;
import java.io.IOException;
import org.glassfish.jersey.jackson.JacksonFeature;
import org.glassfish.jersey.media.multipart.MultiPartFeature;
import org.glassfish.jersey.server.ResourceConfig;
import io.swagger.jaxrs.listing.ApiListingResource;
import io.swagger.jaxrs.listing.SwaggerSerializers;
import io.swagger.jaxrs.config.BeanConfig;
import org.ap.auxpro.rest.filter.AuthorizationRequestFilter;
import org.glassfish.jersey.server.filter.RolesAllowedDynamicFeature;

/* This class was auto-generated by the JavaWriter */
@ApplicationPath("/rest")
public class APRestApplication extends ResourceConfig {

	public APRestApplication() {
		try {
			EConfigProperties.loadProperties();
		} catch (IOException e) {
			System.err.println(e);
		}
		
		packages("org.ap.auxpro.rest");
		
		register(AuthorizationRequestFilter.class);
		register(RolesAllowedDynamicFeature.class);
		register(JacksonFeature.class);
		register(HeadersResponseFilter.class);
		register(MultiPartFeature.class);
		register(ApiListingResource.class);
		register(SwaggerSerializers.class);
		
		BeanConfig beanConfig = new BeanConfig();
		beanConfig.setTitle("ap-auxpro");
		beanConfig.setVersion("1.0.0");
		beanConfig.setSchemes(new String[]{"http"});
		beanConfig.setHost("localhost:8090");
		beanConfig.setBasePath("/rest");
		beanConfig.setResourcePackage("org.ap.auxpro.rest.servlet");
		beanConfig.setScan(true);
		
		String host = EConfigProperties.DB_HOST.getValue();
		String port = EConfigProperties.DB_PORT.getValue();
		String name = EConfigProperties.DB_NAME.getValue();
		Mongo.setUp(host, port, name);
	}

}
