import AppHelper from 'helpers/AppHelper'
import { BaseData } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class AuxiliaryInfosEditEmailData extends BaseData {

	register(obj) {
		super.register(obj)
		
		this.obj.state = {}
	}

	unregister() {
	}

}
let AuxiliaryInfosEditEmailObj = new AuxiliaryInfosEditEmailData()
export default AuxiliaryInfosEditEmailObj
