import React from 'react'
import FAQData from 'components/infos/faq/FAQData'
import './FAQ.scss'

import { Panel, SearchBar } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class FAQ extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		FAQData.register(this)
	}

	componentWillUnmount() {
		FAQData.unregister()
	}

	// _buildTopic(topic) {
	// 	return (
	// 		<div key={topic.id}>
	// 			<h3>{topic.title}</h3>
	// 			<div dangerouslySetInnerHTML={{__html: topic.content}} />
	// 		</div>
	// 	)
	// }

	render() { return (
		<div className='ap-faq ap-infos'>
			
		</div>
	)}

}
export default FAQ
