import AppHelper from 'helpers/AppHelper'
import { BaseData } from 'ap-react-bootstrap'
// import Dispatcher from 'core/Dispatcher'
// import FAQHelper from 'helpers/FAQHelper'
// import Utils from 'utils/Utils'

/* This class was auto-generated by the JavaScriptWriter */
class FAQData extends BaseData {

	register(obj) {
		super.register(obj)
		// Dispatcher.issue('GET_HELP_FAQS', {token: Utils.encode('guest', 'guest')})
		this.obj.state = {}

		// HelpfaqHelper.register('', this, this.buildData.bind(this))
	}

	unregister() {
	}

	buildData() {
		this.setState({
			topics: Utils.map(FAQHelper.getData()).filter(this._filterTopics.bind(this)).sort(this._sortTopics),
			searchBarData: this._buildSearchBarData()
		})
	}

	_filterTopics(topic) {
		if (this.getState('query')) {
			return topic.title.toUpperCase().indexOf(this.getState('query').toUpperCase()) !== -1
		} else {
			return true;
		}
	}
	_sortTopics(topic1, topic2) {
		return topic1.title.localeCompare(topic2.title)
	}
	_buildSearchBarData() { return {
		placeholder: 'Recherche...',
		onChange: this.onLiveSearch.bind(this)
	}}
	onLiveSearch(value) {
		this.setState({query: value})
	}

}
var FAQObj = new FAQData()
export default FAQObj
