package org.ap.auxpro.storage.indisponibility;

import java.util.Date;
import java.util.List;

/* This class was auto-generated by the JavaWriter */
public class IndisponibilityData {

	public String period;
	public String auxiliaryId;
	public Date endDate;
	public Date lastUpdateDate;
	public List<String> days;
	public List<Integer> startTime;
	public List<Integer> endTime;
	public String id;
	public Date creationDate;
	public Date startDate;

	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public String getAuxiliaryId() {
		return this.auxiliaryId;
	}

	public void setAuxiliaryId(String auxiliaryId) {
		this.auxiliaryId = auxiliaryId;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public List<String> getDays() {
		return this.days;
	}

	public void setDays(List<String> days) {
		this.days = days;
	}

	public List<Integer> getStartTime() {
		return this.startTime;
	}

	public void setStartTime(List<Integer> startTime) {
		this.startTime = startTime;
	}

	public List<Integer> getEndTime() {
		return this.endTime;
	}

	public void setEndTime(List<Integer> endTime) {
		this.endTime = endTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

}
