package org.ap.auxpro.storage.indisponibility;

import org.ap.common.storage.IFieldEnum;
import org.ap.common.validators.IValidator;
import org.ap.auxpro.internal.Validators;

/* This class was auto-generated by the JavaWriter */
public enum IndisponibilityFields implements IFieldEnum {

	PERIOD ("period", "String", Validators.NON_NULL.VALIDATOR),
	AUXILIARY_ID ("auxiliaryId", "String", Validators.DEFAULT.VALIDATOR),
	END_DATE ("endDate", "List<Integer>", Validators.DEFAULT.VALIDATOR),
	LAST_UPDATE_DATE ("lastUpdateDate", "List<Integer>", Validators.DEFAULT.VALIDATOR),
	DAYS ("days", "String", Validators.DEFAULT.VALIDATOR),
	START_TIME ("startTime", "Integer", Validators.DEFAULT.VALIDATOR),
	END_TIME ("endTime", "Integer", Validators.DEFAULT.VALIDATOR),
	ID ("id", "String", Validators.DEFAULT.VALIDATOR),
	CREATION_DATE ("creationDate", "List<Integer>", Validators.DEFAULT.VALIDATOR),
	START_DATE ("startDate", "List<Integer>", Validators.DEFAULT.VALIDATOR),
	;

	private String _id;
	private String _type;
	private IValidator _validator;

	private IndisponibilityFields(String id, String type, IValidator validator) {
		_id = id;
		_type = type;
		_validator = validator;
	}

	public String getId() {
		return _id;
	}

	public String getType() {
		return _type;
	}

	public IValidator getValidator() {
		return _validator;
	}

	public static IndisponibilityFields byId(String id) {
		for (IndisponibilityFields value : IndisponibilityFields.values()) {
			if (value.getId().equals(id)) {
				return value;
			}
		}
		return null;
	}

}
