import React from 'react'
import AuxiliaryServiceData from './AuxiliaryServiceData'
import './AuxiliaryService.scss'

/* This class was auto-generated by the JavaScriptWriter */
class AuxiliaryService extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		AuxiliaryServiceData.register(this, this.props.params.serviceId)
	}

	componentWillUnmount() {
		AuxiliaryServiceData.unregister()
	}

	render() {
		return (
			<div className='ap-auxiliaryservice'>
				AuxiliaryService - {this.props.params.serviceId}
			</div>
		)
	}

}
export default AuxiliaryService
