import AppHelper from 'helpers/AppHelper'
import { BaseData } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class AuxiliaryServiceData extends BaseData {

	register(obj, serviceId) {
		super.register(obj)
	}

	unregister() {
	}

}
var AuxiliaryServiceObj = new AuxiliaryServiceData()
export default AuxiliaryServiceObj
