import AppHelper from 'helpers/AppHelper'
import { BaseData } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class AuxiliaryIndisponibilityData extends BaseData {

	register(obj, indisponibilityId) {
		super.register(obj)
		
		this.obj.state = {}
	}

	unregister() {
	}

}
let AuxiliaryIndisponibilityObj = new AuxiliaryIndisponibilityData()
export default AuxiliaryIndisponibilityObj
