package org.ap.auxpro.storage.geozone;

import org.ap.common.storage.IFieldEnum;
import org.ap.common.validators.IValidator;
import org.ap.auxpro.internal.Validators;

/* This class was auto-generated by the JavaWriter */
public enum GeozoneFields implements IFieldEnum {

	AUXILIARY_ID ("auxiliaryId", "String", Validators.DEFAULT.VALIDATOR),
	ADDRESS ("address", "String", Validators.NON_EMPTY_STRING.VALIDATOR),
	LATTITUDE ("lattitude", "Double", Validators.NON_NULL.VALIDATOR),
	CITY ("city", "String", Validators.NON_EMPTY_STRING.VALIDATOR),
	LAST_UPDATE_DATE ("lastUpdateDate", "List<Integer>", Validators.DEFAULT.VALIDATOR),
	POSTAL_CODE ("postalCode", "String", Validators.POSTAL_CODE.VALIDATOR),
	ID ("id", "String", Validators.DEFAULT.VALIDATOR),
	TYPE ("type", "String", Validators.NON_NULL.VALIDATOR),
	RADIUS ("radius", "Integer", Validators.POSITIVE_INTEGER.VALIDATOR),
	CREATION_DATE ("creationDate", "List<Integer>", Validators.DEFAULT.VALIDATOR),
	LONGITUDE ("longitude", "Double", Validators.NON_NULL.VALIDATOR),
	;

	private String _id;
	private String _type;
	private IValidator _validator;

	private GeozoneFields(String id, String type, IValidator validator) {
		_id = id;
		_type = type;
		_validator = validator;
	}

	public String getId() {
		return _id;
	}

	public String getType() {
		return _type;
	}

	public IValidator getValidator() {
		return _validator;
	}

	public static GeozoneFields byId(String id) {
		for (GeozoneFields value : GeozoneFields.values()) {
			if (value.getId().equals(id)) {
				return value;
			}
		}
		return null;
	}

}
