package org.ap.auxpro.storage.geozone;

import org.ap.common.storage.IFieldEnum;
import org.ap.common.validators.ValidatorProvider;
import org.ap.auxpro.internal.Validators;

/* This class was auto-generated by the JavaWriter */
public enum GeozoneFields implements IFieldEnum {

	AUXILIARY_ID ("auxiliaryId", "String", new Validators.DEFAULT()),
	ADDRESS ("address", "String", new Validators.NON_EMPTY_STRING()),
	LATTITUDE ("lattitude", "Double", new Validators.NON_NULL()),
	CITY ("city", "String", new Validators.NON_EMPTY_STRING()),
	LAST_UPDATE_DATE ("lastUpdateDate", "List<Integer>", new Validators.DEFAULT()),
	POSTAL_CODE ("postalCode", "String", new Validators.POSTAL_CODE()),
	ID ("id", "String", new Validators.DEFAULT()),
	TYPE ("type", "String", new Validators.NON_NULL()),
	RADIUS ("radius", "Integer", new Validators.POSITIVE_INTEGER()),
	CREATION_DATE ("creationDate", "List<Integer>", new Validators.DEFAULT()),
	LONGITUDE ("longitude", "Double", new Validators.NON_NULL()),
	;

	private String _id;
	private String _type;
	private ValidatorProvider _validator;

	private GeozoneFields(String id, String type, ValidatorProvider validator) {
		_id = id;
		_type = type;
		_validator = validator;
	}

	public String getId() {
		return _id;
	}

	public String getType() {
		return _type;
	}

	public ValidatorProvider getValidator() {
		return _validator;
	}

	public static GeozoneFields byId(String id) {
		for (GeozoneFields value : GeozoneFields.values()) {
			if (value.getId().equals(id)) {
				return value;
			}
		}
		return null;
	}

}
