import React from 'react'
import CGVData from './CGVData'
import './CGV.scss'
import { Panel, Grid } from 'ap-react-bootstrap'


/* This class was auto-generated by the JavaScriptWriter */
class CGV extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		CGVData.register(this)
	}

	componentWillUnmount() {
		CGVData.unregister()
	}

	render() {
		return (
			<Grid.Container>
				<Panel className='ap-cgv'>
					<Panel.Header>
						<h2>Charte de confidentialité du site internet AuXpros</h2>
					</Panel.Header>
					<Panel.Body>
						<ol type='1'>
						<p>Cette charte de confidentialité concerne les personnes inscrites sur https://www.auxpros.fr, en tant qu’intervenant(e) à domicile ou en tant que Service d’Aide à la Personne (SAP).</p>
							<h3><li>Responsable du traitement</li></h3>
								<p>Tout traitement des données personnelles collectées est effectué sous la responsabilité de : AuXpros, situé au : 46 rue Guersant, 75017 Paris. Les données collectées sont exclusivement destinées à AuXpros et dans le cas des comptes intervenant(e)s aux SAP souhaitant être mis en relation avec ceux-ci dans le cadre d’une mission.</p>
							<h3><li>Quelles sont les informations collectées par AuXpros ?</li></h3>
									<p>Nous recevons et stockons toute données que vous saisissez sur notre site Internet lorsque vous vous inscrivez, complétez votre profil personnel et acceptez ou refusez des missions. Sont concernées, toutes les données permettant de vous identifier (« données personnelles »), comprenant votre prénom, votre nom, votre numéro de téléphone, vos adresses postale et email, le début de votre numéro de sécurité sociale, votre date, ville et pays de naissance pour les comptes intervenant(e) et le nom, la raison sociale et le numéro de société pour les comptes SAP.</p>
							<h3><li>Comment utilisons-nous vos données ?</li></h3>
								<p>Nous utilisons les données personnelles des comptes d’intervenant(e)s pour communiquer avec eux, leur permettre de nous contacter dans le cadre du service client, si nécessaire, pour évaluer l'intérêt pour nos services et site Internet ainsi que pour les améliorer, pour les informer par email ou par courrier postal de nos offres spéciales ou événement particulier, pour solliciter des informations les concernant, par exemple via des sondages et pour exécuter les Conditions Générales d’Utilisation. Nous transférons également leur nom(s), prénom(s), adresse mail et numéro de téléphone aux SAP inscrits qui souhaiteraient entrer en contact avec eux pour leur confier des missions. Nous utilisons les données personnelles des comptes de SAP pour communiquer avec eux, leur permettre de nous contacter dans le cadre du service client, si nécessaire, pour évaluer l'intérêt pour nos services et site Internet ainsi que pour les améliorer, pour les informer par email ou par courrier postal de nos offres spéciales ou événement particulier, pour solliciter des informations les concernant, par exemple via des sondages et pour exécuter les Conditions Générales d’Utilisation. </p>
							<h3><li>Vos choix relatifs à la collecte et l’utilisation de vos données</li></h3>
								<p>Il n’est pas possible d’utiliser un compte inscrit pour trouver ou proposer des missions en l’absence des données demandées sur le profil personnel de l’utilisateur. Il est possible d’avoir accès et de mettre ses coordonnées à jour sur la page « Profil » du site internet Auxpros.fr. Il est possible de clore son compte AuXpros par courrier postal à l’adresse suivante : Société AuXpros 46 rue Guersant 75017 Paris. Veuillez noter qu'après avoir fermé votre compte, vous ne pourrez plus vous connecter ou avoir accès à vos données personnelles. Toutefois, vous pouvez créer un nouveau compte à tout moment.</p>
							<h3><li>Vos droits relatifs à la loi Informatique et Libertés</li></h3>
									<p>Conformément à la loi Informatique et Libertés du 6 janvier 1978, vous disposez d'un droit d'accès, de rectification, d'opposition et de suppression aux données personnelles vous concernant. Pour l'exercer, vous pouvez vous rendre directement sur www.auxpros.fr pour changer les informations de votre profil ou adresser votre demande en précisant vos nom, prénom et email par courrier postal à l’adresse suivante : Société AuXpros 46 rue Guersant 75017 Paris. Conformément à la réglementation en vigueur, votre demande doit être signée et accompagnée de la photocopie d'une pièce d'identité portant votre signature. Pour le désabonnement à nos communications par email, il suffit de cliquer sur le lien de désabonnement situé en bas de nos emails.</p>
								
							<h3><li>Notices et révisions</li></h3>
									<p>Notre activité est en évolution constante et la présente politique de protection des informations personnelles et nos conditions générales de vente changent également. Nous pourrions être amenés à vous envoyer régulièrement des rappels sur la politique applicable en la matière (sauf si vous nous demandez de ne pas le faire) mais nous vous invitons à consulter notre site Internet régulièrement pour vous informer des changements les plus récents. Sauf mention contraire, notre politique de protection des informations personnelles s'applique à l'utilisation de toutes les informations que nous avons collectées vous concernant ou concernant votre compte. Nous tenons nos promesses et nous ne changerons jamais de manière substantielle nos politiques et nos pratiques dans un sens qui réduirait la protection des informations clients collectées par le passé, sans le consentement des clients concernés.</p>
						</ol>
					</Panel.Body>
				</Panel>
			</Grid.Container>
		)
	}
}
export default CGV
