import AppHelper from 'helpers/AppHelper'
import { BaseData } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class ServicesServiceData extends BaseData {

	register(obj) {
		super.register(obj)
	}

	unregister() {
	}

}
let ServicesServiceObj = new ServicesServiceData()
export default ServicesServiceObj
