import React from 'react'
import AuxiliaryInfosData from 'components/auxiliary/infos/AuxiliaryInfosData'
import './AuxiliaryInfos.scss'

/* This class was auto-generated by the JavaScriptWriter */
class AuxiliaryInfos extends React.Component {

	constructor(props) {
		super(props)
	}

	componentWillMount() {
		AuxiliaryInfosData.register(this)
	}

	componentWillUnmount() {
		AuxiliaryInfosData.unregister()
	}

	render() {
		return (
			<div className='ap-auxiliaryinfos'>
				AuxiliaryInfos
			</div>
		)
	}

}
export default AuxiliaryInfos
