package org.ap.auxpro.rest.servlet;

import javax.ws.rs.*;
import javax.ws.rs.core.*;
import javax.ws.rs.core.Response.*;
import org.ap.web.rest.servlet.APServletBase;
import org.ap.auxpro.bean.HelpTopicBean;
import org.ap.auxpro.storage.HelptopicData;
import org.ap.auxpro.storage.HelptopicCollection;
import org.ap.web.internal.APWebException;
import java.util.List;
import java.util.ArrayList;
import org.ap.auxpro.bean.HelpFaqBean;
import org.ap.auxpro.storage.HelpfaqData;
import org.ap.auxpro.storage.HelpfaqCollection;

/* This class was auto-generated by the JavaWriter */
@Path("/help")
public class HelpServlet extends APServletBase {

	public static final String PATH = "/help";

	@GET
	@Path("/topics")
	@Produces({MediaType.APPLICATION_JSON})
	public Response getHelpTopics(@Context SecurityContext sc) {
		try {
			List<HelptopicData> datas = HelptopicCollection.getAll();
			
			List<HelpTopicBean> beanList = new ArrayList<HelpTopicBean>();
			for (HelptopicData data : datas) {
				HelpTopicBean bean = new HelpTopicBean();
				bean.id = data.getId();
				bean.title = data.getTitle();
				bean.content = data.getContent();
				
				beanList.add(bean);
			}
			
			return Response.status(Status.OK).entity(beanList.toArray(new HelpTopicBean[beanList.size()])).build();
			
		} catch (APWebException e) {
			return sendException(e);
		} catch (Exception e) {
			return Response.status(Status.INTERNAL_SERVER_ERROR).build();
		}
	}

	@GET
	@Path("/faqs")
	@Produces({MediaType.APPLICATION_JSON})
	public Response getHelpFaqs(@Context SecurityContext sc) {
		try {
			List<HelpfaqData> datas = HelpfaqCollection.getAll();
			
			List<HelpFaqBean> beanList = new ArrayList<HelpFaqBean>();
			for (HelpfaqData data : datas) {
				HelpFaqBean bean = new HelpFaqBean();
				bean.id = data.getId();
				bean.title = data.getTitle();
				bean.content = data.getContent();
				
				beanList.add(bean);
			}
			
			return Response.status(Status.OK).entity(beanList.toArray(new HelpFaqBean[beanList.size()])).build();
			
		} catch (APWebException e) {
			return sendException(e);
		} catch (Exception e) {
			return Response.status(Status.INTERNAL_SERVER_ERROR).build();
		}
	}

}
