package org.ap.auxpro.rest.servlet;

import javax.ws.rs.*;
import javax.ws.rs.core.*;
import javax.ws.rs.core.Response.*;
import org.ap.web.rest.servlet.APServletBase;
import org.ap.auxpro.bean.MissionBean;
import org.ap.auxpro.storage.MissionData;
import org.ap.auxpro.storage.MissionCollection;
import org.ap.web.internal.APWebException;
import javax.annotation.security.RolesAllowed;
import org.ap.common.TimeHelper;

/* This class was auto-generated by the JavaWriter */
@Path("/missions")
public class MissionServlet extends APServletBase {

	public static final String PATH = "/missions";

	@GET
	@Path("/{id}")
	@Produces({MediaType.APPLICATION_JSON})
	@RolesAllowed("apauth")
	public Response getMission(@Context SecurityContext sc, @PathParam("id") final String id) {
		try {
			MissionData data = MissionCollection.getById(id);
			if(data == null) {
				return Response.status(Status.NOT_FOUND).build();
			}
			MissionBean bean = new MissionBean();
			bean.date = data.getDate();
			bean.auxStatus = data.getAuxStatus();
			bean.auxStatusChanged = data.getAuxStatusChanged();
			bean.auxiliaryId = data.getAuxiliaryId();
			bean.hideToAux = data.getHideToAux();
			bean.lastUpdateDate = data.getLastUpdateDate();
			bean.sadStatusChanged = data.getSadStatusChanged();
			bean.creationDate = data.getCreationDate();
			bean.customerId = data.getCustomerId();
			bean.sadStatus = data.getSadStatus();
			bean.id = data.getId();
			bean.serviceId = data.getServiceId();
			bean.interventionId = data.getInterventionId();
			bean.hideToSad = data.getHideToSad();
			
			return Response.status(Status.OK).entity(bean).build();
			
		} catch (APWebException e) {
			return sendException(e);
		} catch (Exception e) {
			return Response.status(Status.INTERNAL_SERVER_ERROR).build();
		}
	}

	@PUT
	@Path("/{id}")
	@Consumes({MediaType.APPLICATION_JSON})
	@RolesAllowed("apauth")
	public Response putMission(@Context SecurityContext sc, @PathParam("id") final String id, MissionBean missionBean) {
		try {
			// Get actual data object
			MissionData data = MissionCollection.getById(id);
			// Check data exists
			if (data == null) {
				throw new APWebException("mission not found", "AP_MISSION_NOTFOUND", Status.BAD_REQUEST);
			}
			// Update the data object
			data.setLastUpdateDate(TimeHelper.nowDateTimeIntegers());
			data.setDate(missionBean.date);
			data.setAuxStatus(missionBean.auxStatus);
			data.setAuxStatusChanged(missionBean.auxStatusChanged);
			data.setAuxiliaryId(missionBean.auxiliaryId);
			data.setHideToAux(missionBean.hideToAux);
			data.setSadStatusChanged(missionBean.sadStatusChanged);
			data.setCustomerId(missionBean.customerId);
			data.setSadStatus(missionBean.sadStatus);
			data.setServiceId(missionBean.serviceId);
			data.setInterventionId(missionBean.interventionId);
			data.setHideToSad(missionBean.hideToSad);
			// Store the updated data object
			MissionCollection.updateNull(data);
			// Send the response
			return Response.status(Status.OK).build();
			
		} catch (APWebException e) {
			return sendException(e);
		} catch (Exception e) {
			return Response.status(Status.INTERNAL_SERVER_ERROR).build();
		}
	}

	@DELETE
	@Path("/{id}")
	@RolesAllowed("apauth")
	public Response deleteMission(@Context SecurityContext sc, @PathParam("id") final String id) {
		try {
			// Try to delete the entity
			if (!MissionCollection.deleteById(id)) {
				throw new APWebException("mission not found", "AP_MISSION_NOTFOUND", Status.BAD_REQUEST);
			}
			// Send the response
			return Response.status(Status.OK).build();
			
		} catch (APWebException e) {
			return sendException(e);
		} catch (Exception e) {
			return Response.status(Status.INTERNAL_SERVER_ERROR).build();
		}
	}

}
