import AppHelper from 'helpers/AppHelper'
import { BaseData } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class AuxiliaryOfferData extends BaseData {

	register(obj, offerId) {
		super.register(obj)
		
		this.obj.state = {}
	}

	unregister() {
	}

}
var AuxiliaryOfferObj = new AuxiliaryOfferData()
export default AuxiliaryOfferObj
