package org.ap.auxpro.bean;

/* This class was auto-generated by the JavaWriter */
public class APAuthInfoBean {

	public String username;
	public String entityId;
	public String type;
	public String email;

}
