package org.ap.auxpro.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;

/* This class was auto-generated by the JavaWriter */
@JsonIgnoreProperties(ignoreUnknown=true)
public class AuxiliaryCredentialsBean {

	public List<Integer> lastUpdateDate;
	public Boolean emailChecked;
	public String id;
	public List<Integer> creationDate;
	public String email;
	public String username;
	public String password;

}
