package org.ap.auxpro.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;
import org.ap.auxpro.storage.auxiliary.AuxiliaryData;
import org.ap.common.time.TimeHelper;
import org.ap.common.exception.APWebException;

/* This class was auto-generated by the JavaWriter */
@JsonIgnoreProperties(ignoreUnknown=true)
public class AuxiliaryQuestionaryBean {

	public List<Integer> skillAnswers;
	public List<Integer> lastUpdateDate;
	public String id;
	public List<Integer> creationDate;

	public AuxiliaryQuestionaryBean() {
	}

	public AuxiliaryQuestionaryBean(AuxiliaryData data) {
		skillAnswers = data.getSkillAnswers();
		lastUpdateDate = TimeHelper.toIntegers(data.getLastUpdateDate());
		id = data.getId();
		creationDate = TimeHelper.toIntegers(data.getCreationDate());
	}

	public AuxiliaryData toData() {
		AuxiliaryData data = new AuxiliaryData();
		fillData(data);
		return data;
	}

	public void fillData(AuxiliaryData data) {
		data.setSkillAnswers(skillAnswers);
	}

	public void check() throws APWebException {
	}

}
