package org.ap.auxpro.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;
import org.ap.auxpro.storage.auxiliary.AuxiliaryData;
import org.ap.common.time.TimeHelper;
import org.ap.common.exception.APWebException;
import org.ap.common.exception.APWebError;
import java.util.ArrayList;
import javax.ws.rs.core.Response.Status;
import org.ap.auxpro.storage.auxiliary.AuxiliaryFields;

/* This class was auto-generated by the JavaWriter */
@JsonIgnoreProperties(ignoreUnknown=true)
public class AuxiliaryPutBean {

	public String country;
	public String lastName;
	public String civility;
	public String city;
	public List<Integer> lastUpdateDate;
	public String postalCode;
	public Boolean isTutoSkipped;
	public String description;
	public String socialNumber;
	public Boolean notifyOffersSms;
	public Boolean notifyAuxpros;
	public String birthCountry;
	public List<String> diploma;
	public String id;
	public Double longitude;
	public String address;
	public Double lattitude;
	public Boolean notifyPartners;
	public String birthCity;
	public String avatar;
	public List<Integer> creationDate;
	public List<Integer> birthDate;
	public String firstName;
	public String nationality;
	public String isEntrepreneur;
	public String phone;
	public Boolean notifyOffersMail;

	public AuxiliaryPutBean() {
	}

	public AuxiliaryPutBean(AuxiliaryData data) {
		country = data.getCountry();
		lastName = data.getLastName();
		civility = data.getCivility();
		city = data.getCity();
		lastUpdateDate = TimeHelper.toIntegers(data.getLastUpdateDate());
		postalCode = data.getPostalCode();
		isTutoSkipped = data.getIsTutoSkipped();
		description = data.getDescription();
		socialNumber = data.getSocialNumber();
		notifyOffersSms = data.getNotifyOffersSms();
		notifyAuxpros = data.getNotifyAuxpros();
		birthCountry = data.getBirthCountry();
		diploma = data.getDiploma();
		id = data.getId();
		longitude = data.getLongitude();
		address = data.getAddress();
		lattitude = data.getLattitude();
		notifyPartners = data.getNotifyPartners();
		birthCity = data.getBirthCity();
		avatar = data.getAvatar();
		creationDate = TimeHelper.toIntegers(data.getCreationDate());
		birthDate = TimeHelper.toIntegers(data.getBirthDate());
		firstName = data.getFirstName();
		nationality = data.getNationality();
		isEntrepreneur = data.getIsEntrepreneur();
		phone = data.getPhone();
		notifyOffersMail = data.getNotifyOffersMail();
	}

	public AuxiliaryData toData() {
		AuxiliaryData data = new AuxiliaryData();
		fillData(data);
		return data;
	}

	public void fillData(AuxiliaryData data) {
		data.setCountry(country);
		data.setLastName(lastName);
		data.setCivility(civility);
		data.setCity(city);
		data.setPostalCode(postalCode);
		data.setIsTutoSkipped(isTutoSkipped);
		data.setDescription(description);
		data.setSocialNumber(socialNumber);
		data.setNotifyOffersSms(notifyOffersSms);
		data.setNotifyAuxpros(notifyAuxpros);
		data.setBirthCountry(birthCountry);
		data.setDiploma(diploma);
		data.setLongitude(longitude);
		data.setAddress(address);
		data.setLattitude(lattitude);
		data.setNotifyPartners(notifyPartners);
		data.setBirthCity(birthCity);
		data.setAvatar(avatar);
		data.setBirthDate(TimeHelper.toDate(birthDate));
		data.setFirstName(firstName);
		data.setNationality(nationality);
		data.setIsEntrepreneur(isEntrepreneur);
		data.setPhone(phone);
		data.setNotifyOffersMail(notifyOffersMail);
	}

	public void check() throws APWebException {
		List<APWebError> errors = new ArrayList<APWebError>();
		if (AuxiliaryFields.COUNTRY.getValidator().getState(country)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'country'"));
		}
		if (AuxiliaryFields.LAST_NAME.getValidator().getState(lastName)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'lastName'"));
		}
		if (AuxiliaryFields.CIVILITY.getValidator().getState(civility)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'civility'"));
		}
		if (AuxiliaryFields.CITY.getValidator().getState(city)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'city'"));
		}
		if (AuxiliaryFields.POSTAL_CODE.getValidator().getState(postalCode)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'postalCode'"));
		}
		if (AuxiliaryFields.DESCRIPTION.getValidator().getState(description)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'description'"));
		}
		if (AuxiliaryFields.SOCIAL_NUMBER.getValidator().getState(socialNumber)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'socialNumber'"));
		}
		if (AuxiliaryFields.BIRTH_COUNTRY.getValidator().getState(birthCountry)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'birthCountry'"));
		}
		if (AuxiliaryFields.DIPLOMA.getValidator().getState(diploma)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'diploma'"));
		}
		if (AuxiliaryFields.ADDRESS.getValidator().getState(address)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'address'"));
		}
		if (AuxiliaryFields.BIRTH_CITY.getValidator().getState(birthCity)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'birthCity'"));
		}
		if (AuxiliaryFields.BIRTH_DATE.getValidator().getState(birthDate)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'birthDate'"));
		}
		if (AuxiliaryFields.FIRST_NAME.getValidator().getState(firstName)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'firstName'"));
		}
		if (AuxiliaryFields.NATIONALITY.getValidator().getState(nationality)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'nationality'"));
		}
		if (AuxiliaryFields.IS_ENTREPRENEUR.getValidator().getState(isEntrepreneur)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'isEntrepreneur'"));
		}
		if (AuxiliaryFields.PHONE.getValidator().getState(phone)) {
			errors.add(new APWebError("AP_AUXILIARY_INVALID_FIELDS", "Invalid field 'phone'"));
		}
		if (errors.size() > 0) {
			throw new APWebException("AP_AUXILIARY_INVALID_FIELDS", "Invalid fields within 'auxiliary'", errors, Status.BAD_REQUEST);
		}
	}

}
