package org.ap.auxpro.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;

/* This class was auto-generated by the JavaWriter */
@JsonIgnoreProperties(ignoreUnknown=true)
public class AuxiliaryQuestionaryBean {

	public List<Integer> skillAnswers;
	public List<Integer> lastUpdateDate;
	public String id;
	public List<Integer> creationDate;

}
