package org.ap.auxpro.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;

/* This class was auto-generated by the JavaWriter */
@JsonIgnoreProperties(ignoreUnknown=true)
public class AuxiliaryGetBean {

	public String country;
	public String lastName;
	public String civility;
	public String city;
	public List<Integer> lastUpdateDate;
	public String postalCode;
	public Boolean isTutoSkipped;
	public String description;
	public String socialNumber;
	public List<Integer> accountExpiryDate;
	public Integer profilProgression;
	public Integer skillShopping;
	public Boolean notifyOffersSms;
	public Boolean notifyAuxpros;
	public String birthCountry;
	public Boolean profilCompleted;
	public Integer skillDoityourself;
	public List<String> diploma;
	public String id;
	public Double longitude;
	public Integer skillNursing;
	public String address;
	public Double lattitude;
	public String accountType;
	public Boolean notifyPartners;
	public String birthCity;
	public String avatar;
	public Boolean areSkillSet;
	public List<Integer> creationDate;
	public List<Integer> birthDate;
	public Integer skillChildhood;
	public Integer skillCompagny;
	public String firstName;
	public List<Integer> skillAnswers;
	public String nationality;
	public String isEntrepreneur;
	public String phone;
	public Integer skillAdministrative;
	public Integer skillHousework;
	public String idCardNumber;
	public Boolean notifyOffersMail;

}
