package org.ap.auxpro.bean;

import java.util.List;

/* This class was auto-generated by the JavaWriter */
public class AuxiliaryCredentialsBean {

	public List<Integer> lastUpdateDate;
	public Boolean emailChecked;
	public String id;
	public List<Integer> creationDate;
	public String email;
	public String username;
	public String password;

}
