package org.ap.auxpro.bean;

/* This class was auto-generated by the JavaWriter */
public class GeozoneBean {

	public String auxiliaryId;
	public String address;
	public Double lattitude;
	public String city;
	public String postalCode;
	public String id;
	public String type;
	public Integer radius;
	public Double longitude;

}
