package org.ap.auxpro.bean;

import java.util.List;

/* This class was auto-generated by the JavaWriter */
public class HelpFaqBean {

	public List<Integer> lastUpdateDate;
	public String id;
	public String title;
	public List<Integer> creationDate;
	public String content;

}
