package org.ap.auxpro.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;
import org.ap.auxpro.storage.intervention.InterventionData;
import org.ap.common.time.TimeHelper;
import org.ap.common.validators.EValidatorState;
import org.ap.common.validators.ValidationState;
import org.ap.common.exception.APWebException;
import org.ap.common.exception.APWebError;
import java.util.ArrayList;
import javax.ws.rs.core.Response.Status;
import org.ap.auxpro.storage.intervention.InterventionFields;

/* This class was auto-generated by the JavaWriter */
@JsonIgnoreProperties(ignoreUnknown=true)
public class InterventionBean {

	public String auxiliaryId;
	public String period;
	public List<Integer> endDate;
	public List<Integer> lastUpdateDate;
	public List<Integer> sadStatusChanged;
	public List<Integer> creationDate;
	public String missionType;
	public String sadStatus;
	public List<String> days;
	public List<String> diplomas;
	public List<Integer> startTime;
	public List<Integer> endTime;
	public String id;
	public Boolean hideToSad;
	public List<Integer> startDate;
	public String customerId;
	public String serviceId;

	public InterventionBean() {
	}

	public InterventionBean(InterventionData data) {
		auxiliaryId = data.getAuxiliaryId();
		period = data.getPeriod();
		endDate = TimeHelper.toIntegers(data.getEndDate());
		lastUpdateDate = TimeHelper.toIntegers(data.getLastUpdateDate());
		sadStatusChanged = TimeHelper.toIntegers(data.getSadStatusChanged());
		creationDate = TimeHelper.toIntegers(data.getCreationDate());
		missionType = data.getMissionType();
		sadStatus = data.getSadStatus();
		days = data.getDays();
		diplomas = data.getDiplomas();
		startTime = data.getStartTime();
		endTime = data.getEndTime();
		id = data.getId();
		hideToSad = data.getHideToSad();
		startDate = TimeHelper.toIntegers(data.getStartDate());
		customerId = data.getCustomerId();
		serviceId = data.getServiceId();
	}

	public InterventionData toData() {
		InterventionData data = new InterventionData();
		fillData(data);
		return data;
	}

	public void fillData(InterventionData data) {
		data.setAuxiliaryId(auxiliaryId);
		data.setPeriod(period);
		data.setEndDate(TimeHelper.toDate(endDate));
		data.setSadStatusChanged(TimeHelper.toDate(sadStatusChanged));
		data.setMissionType(missionType);
		data.setSadStatus(sadStatus);
		data.setDays(days);
		data.setDiplomas(diplomas);
		data.setStartTime(startTime);
		data.setEndTime(endTime);
		data.setHideToSad(hideToSad);
		data.setStartDate(TimeHelper.toDate(startDate));
		data.setCustomerId(customerId);
		data.setServiceId(serviceId);
	}

	public void check() throws APWebException {
		List<APWebError> errors = new ArrayList<APWebError>();
		ValidationState missionTypeState = InterventionFields.MISSION_TYPE.getValidator().VALIDATOR().check(missionType);
		if (!missionTypeState.getState().equals(EValidatorState.SUCCESS)) {
			errors.add(new APWebError("AP_INTERVENTION_INVALID_FIELDS", "Invalid field 'missionType'"));
		}
		if (errors.size() > 0) {
			throw new APWebException("AP_INTERVENTION_INVALID_FIELDS", "Invalid fields within 'intervention'", errors, Status.BAD_REQUEST);
		}
	}

}
