package org.ap.auxpro.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;

/* This class was auto-generated by the JavaWriter */
@JsonIgnoreProperties(ignoreUnknown=true)
public class MissionBean {

	public String auxiliaryId;
	public String customerId;
	public String serviceId;
	public String interventionId;
	public List<Integer> date;
	public String auxStatus;
	public List<Integer> auxStatusChanged;
	public Boolean hideToAux;
	public List<Integer> lastUpdateDate;
	public String sadStatus;
	public List<Integer> sadStatusChanged;
	public String id;
	public List<Integer> creationDate;
	public Boolean hideToSad;

}
