package org.ap.auxpro.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;
import org.ap.auxpro.storage.mission.MissionData;
import org.ap.common.time.TimeHelper;
import org.ap.common.web.exception.APWebException;

/* This class was auto-generated by the JavaWriter */
@JsonIgnoreProperties(ignoreUnknown=true)
public class MissionBean {

	public String auxiliaryId;
	public String customerId;
	public String serviceId;
	public String interventionId;
	public List<Integer> date;
	public String auxStatus;
	public List<Integer> auxStatusChanged;
	public Boolean hideToAux;
	public List<Integer> lastUpdateDate;
	public String sadStatus;
	public List<Integer> sadStatusChanged;
	public String id;
	public List<Integer> creationDate;
	public Boolean hideToSad;

	public MissionBean() {
	}

	public MissionBean(MissionData data) {
		auxiliaryId = data.getAuxiliaryId();
		customerId = data.getCustomerId();
		serviceId = data.getServiceId();
		interventionId = data.getInterventionId();
		date = TimeHelper.toIntegers(data.getDate());
		auxStatus = data.getAuxStatus();
		auxStatusChanged = TimeHelper.toIntegers(data.getAuxStatusChanged());
		hideToAux = data.getHideToAux();
		lastUpdateDate = TimeHelper.toIntegers(data.getLastUpdateDate());
		sadStatus = data.getSadStatus();
		sadStatusChanged = TimeHelper.toIntegers(data.getSadStatusChanged());
		id = data.getId();
		creationDate = TimeHelper.toIntegers(data.getCreationDate());
		hideToSad = data.getHideToSad();
	}

	public MissionData toData() {
		MissionData data = new MissionData();
		fillData(data);
		return data;
	}

	public void fillData(MissionData data) {
		data.setAuxiliaryId(auxiliaryId);
		data.setCustomerId(customerId);
		data.setServiceId(serviceId);
		data.setInterventionId(interventionId);
		data.setDate(TimeHelper.toDate(date));
		data.setAuxStatus(auxStatus);
		data.setAuxStatusChanged(TimeHelper.toDate(auxStatusChanged));
		data.setHideToAux(hideToAux);
		data.setSadStatus(sadStatus);
		data.setSadStatusChanged(TimeHelper.toDate(sadStatusChanged));
		data.setHideToSad(hideToSad);
	}

	public void check() throws APWebException {
	}

}
