package org.ap.auxpro.bean;

import java.util.List;

/* This class was auto-generated by the JavaWriter */
public class OfferBean {

	public String auxStatus;
	public List<Integer> auxStatusChanged;
	public String auxiliaryId;
	public Boolean hideToAux;
	public String customerId;
	public String sadStatus;
	public List<Integer> sadStatusChanged;
	public String id;
	public String serviceId;
	public List<Integer> creationDate;
	public String interventionId;
	public Boolean hideToSad;

}
