package org.ap.auxpro.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;

/* This class was auto-generated by the JavaWriter */
@JsonIgnoreProperties(ignoreUnknown=true)
public class OfferPostBean {

	public String auxiliaryId;
	public List<Integer> lastUpdateDate;
	public String customerId;
	public String id;
	public String serviceId;
	public List<Integer> creationDate;
	public String interventionId;

}
