package org.ap.auxpro.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;
import org.ap.auxpro.storage.offer.OfferData;
import org.ap.common.time.TimeHelper;

/* This class was auto-generated by the JavaWriter */
@JsonIgnoreProperties(ignoreUnknown=true)
public class OfferPostBean {

	public String auxiliaryId;
	public String customerId;
	public String serviceId;
	public String interventionId;
	public List<Integer> lastUpdateDate;
	public String id;
	public List<Integer> creationDate;

	public OfferPostBean() {
	}

	public OfferPostBean(OfferData data) {
		auxiliaryId = data.getAuxiliaryId();
		customerId = data.getCustomerId();
		serviceId = data.getServiceId();
		interventionId = data.getInterventionId();
		lastUpdateDate = TimeHelper.toIntegers(data.getLastUpdateDate());
		id = data.getId();
		creationDate = TimeHelper.toIntegers(data.getCreationDate());
	}

	public OfferData toData() {
		OfferData data = new OfferData();
		fillData(data);
		return data;
	}

	public void fillData(OfferData data) {
		data.setAuxiliaryId(auxiliaryId);
		data.setCustomerId(customerId);
		data.setServiceId(serviceId);
		data.setInterventionId(interventionId);
	}

}
