package org.ap.auxpro.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;
import org.ap.auxpro.storage.promotioncode.PromotioncodeData;
import org.ap.common.time.TimeHelper;
import org.ap.common.exception.APWebException;

/* This class was auto-generated by the JavaWriter */
@JsonIgnoreProperties(ignoreUnknown=true)
public class PromotionCodeHiddenBean {

	public List<Integer> validityDate;
	public List<Integer> lastUpdateDate;
	public String name;
	public String id;
	public List<Integer> creationDate;

	public PromotionCodeHiddenBean() {
	}

	public PromotionCodeHiddenBean(PromotioncodeData data) {
		validityDate = TimeHelper.toIntegers(data.getValidityDate());
		lastUpdateDate = TimeHelper.toIntegers(data.getLastUpdateDate());
		name = data.getName();
		id = data.getId();
		creationDate = TimeHelper.toIntegers(data.getCreationDate());
	}

	public PromotioncodeData toData() {
		PromotioncodeData data = new PromotioncodeData();
		fillData(data);
		return data;
	}

	public void fillData(PromotioncodeData data) {
		data.setValidityDate(TimeHelper.toDate(validityDate));
		data.setName(name);
	}

	public void check() throws APWebException {
	}

}
