package org.ap.auxpro.bean;

/* This class was auto-generated by the JavaWriter */
public class ServiceCredentialsBean {

	public String id;
	public String email;
	public String username;
	public String password;

}
