import AppHelper from 'helpers/AppHelper'
import { BaseData } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class ServiceCustomerData extends BaseData {

	register(obj, customerId) {
		super.register(obj)
		
		this.obj.state = {}
	}

	unregister() {
	}

}
var ServiceCustomerObj = new ServiceCustomerData()
export default ServiceCustomerObj
