import AppHelper from 'helpers/AppHelper'
import { BaseData } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class AuxiliaryIndisponibilityEditData extends BaseData {

	register(obj, indisponibilityId) {
		super.register(obj)
		
		this.obj.state = {}
	}

	unregister() {
	}

}
var AuxiliaryIndisponibilityEditObj = new AuxiliaryIndisponibilityEditData()
export default AuxiliaryIndisponibilityEditObj
